/* tslint:disable */
/* eslint-disable */
/**
 * BMM Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BrowseResponse,
  DocumentListAudiobooks,
  DocumentListEvents,
  DocumentListPodcasts,
} from '../models';
import {
    BrowseResponseFromJSON,
    BrowseResponseToJSON,
    DocumentListAudiobooksFromJSON,
    DocumentListAudiobooksToJSON,
    DocumentListEventsFromJSON,
    DocumentListEventsToJSON,
    DocumentListPodcastsFromJSON,
    DocumentListPodcastsToJSON,
} from '../models';

export interface BrowseAudiobooksGetRequest {
    skip?: number;
    take?: number;
}

export interface BrowseEventsGetRequest {
    skip?: number;
    take?: number;
}

/**
 * 
 */
export class BrowseApi extends runtime.BaseAPI {

    /**
     */
    async browseAudiobooksGetRaw(requestParameters: BrowseAudiobooksGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DocumentListAudiobooks>> {
        const queryParameters: any = {};

        if (requestParameters.skip !== undefined) {
            queryParameters['Skip'] = requestParameters.skip;
        }

        if (requestParameters.take !== undefined) {
            queryParameters['Take'] = requestParameters.take;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/Browse/audiobooks`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DocumentListAudiobooksFromJSON(jsonValue));
    }

    /**
     */
    async browseAudiobooksGet(requestParameters: BrowseAudiobooksGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DocumentListAudiobooks> {
        const response = await this.browseAudiobooksGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async browseEventsGetRaw(requestParameters: BrowseEventsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DocumentListEvents>> {
        const queryParameters: any = {};

        if (requestParameters.skip !== undefined) {
            queryParameters['Skip'] = requestParameters.skip;
        }

        if (requestParameters.take !== undefined) {
            queryParameters['Take'] = requestParameters.take;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/Browse/events`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DocumentListEventsFromJSON(jsonValue));
    }

    /**
     */
    async browseEventsGet(requestParameters: BrowseEventsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DocumentListEvents> {
        const response = await this.browseEventsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async browseGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<BrowseResponse>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/Browse`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(BrowseResponseFromJSON));
    }

    /**
     */
    async browseGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<BrowseResponse>> {
        const response = await this.browseGetRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async browseMusicGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DocumentListPodcasts>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/Browse/music`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DocumentListPodcastsFromJSON(jsonValue));
    }

    /**
     */
    async browseMusicGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DocumentListPodcasts> {
        const response = await this.browseMusicGetRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async browsePodcastsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DocumentListPodcasts>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/Browse/podcasts`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DocumentListPodcastsFromJSON(jsonValue));
    }

    /**
     */
    async browsePodcastsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DocumentListPodcasts> {
        const response = await this.browsePodcastsGetRaw(initOverrides);
        return await response.value();
    }

}
