/* tslint:disable */
/* eslint-disable */
/**
 * BMM Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateTrackPlayedEventsCommandEvent,
  GetYearInReviewOverviewSlide,
} from '../models';
import {
    CreateTrackPlayedEventsCommandEventFromJSON,
    CreateTrackPlayedEventsCommandEventToJSON,
    GetYearInReviewOverviewSlideFromJSON,
    GetYearInReviewOverviewSlideToJSON,
} from '../models';

export interface StatisticsTrackPlayedPostRequest {
    createTrackPlayedEventsCommandEvent: Array<CreateTrackPlayedEventsCommandEvent>;
}

/**
 * 
 */
export class StatisticsApi extends runtime.BaseAPI {

    /**
     */
    async statisticsTrackPlayedPostRaw(requestParameters: StatisticsTrackPlayedPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.createTrackPlayedEventsCommandEvent === null || requestParameters.createTrackPlayedEventsCommandEvent === undefined) {
            throw new runtime.RequiredError('createTrackPlayedEventsCommandEvent','Required parameter requestParameters.createTrackPlayedEventsCommandEvent was null or undefined when calling statisticsTrackPlayedPost.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json-patch+json';

        const response = await this.request({
            path: `/Statistics/track/played`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters.createTrackPlayedEventsCommandEvent.map(CreateTrackPlayedEventsCommandEventToJSON),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async statisticsTrackPlayedPost(requestParameters: StatisticsTrackPlayedPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.statisticsTrackPlayedPostRaw(requestParameters, initOverrides);
    }

    /**
     */
    async statisticsYearInReviewFkGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/Statistics/year-in-review/fk`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async statisticsYearInReviewFkGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.statisticsYearInReviewFkGetRaw(initOverrides);
    }

    /**
     */
    async statisticsYearInReviewHoursGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/Statistics/year-in-review/hours`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async statisticsYearInReviewHoursGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.statisticsYearInReviewHoursGetRaw(initOverrides);
    }

    /**
     */
    async statisticsYearInReviewOverviewGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<GetYearInReviewOverviewSlide>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/Statistics/year-in-review/overview`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(GetYearInReviewOverviewSlideFromJSON));
    }

    /**
     */
    async statisticsYearInReviewOverviewGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<GetYearInReviewOverviewSlide>> {
        const response = await this.statisticsYearInReviewOverviewGetRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async statisticsYearInReviewSongsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/Statistics/year-in-review/songs`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async statisticsYearInReviewSongsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.statisticsYearInReviewSongsGetRaw(initOverrides);
    }

}
