/* tslint:disable */
/* eslint-disable */
/**
 * BMM Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AlbumTranslationMeta
 */
export interface AlbumTranslationMeta {
    /**
     * 
     * @type {boolean}
     * @memberof AlbumTranslationMeta
     */
    isVisible?: boolean;
}

/**
 * Check if a given object implements the AlbumTranslationMeta interface.
 */
export function instanceOfAlbumTranslationMeta(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AlbumTranslationMetaFromJSON(json: any): AlbumTranslationMeta {
    return AlbumTranslationMetaFromJSONTyped(json, false);
}

export function AlbumTranslationMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): AlbumTranslationMeta {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'isVisible': !exists(json, 'is_visible') ? undefined : json['is_visible'],
    };
}

export function AlbumTranslationMetaToJSON(value?: AlbumTranslationMeta | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'is_visible': value.isVisible,
    };
}

