/* tslint:disable */
/* eslint-disable */
/**
 * BMM Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ApiOverviewModelStatus } from './ApiOverviewModelStatus';
import {
    ApiOverviewModelStatusFromJSON,
    ApiOverviewModelStatusFromJSONTyped,
    ApiOverviewModelStatusToJSON,
} from './ApiOverviewModelStatus';
import type { LanguageEnum } from './LanguageEnum';
import {
    LanguageEnumFromJSON,
    LanguageEnumFromJSONTyped,
    LanguageEnumToJSON,
} from './LanguageEnum';

/**
 * 
 * @export
 * @interface ApiOverviewModel
 */
export interface ApiOverviewModel {
    /**
     * 
     * @type {string}
     * @memberof ApiOverviewModel
     */
    readonly name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiOverviewModel
     */
    documentation?: string | null;
    /**
     * 
     * @type {ApiOverviewModelStatus}
     * @memberof ApiOverviewModel
     */
    systemStatus?: ApiOverviewModelStatus;
    /**
     * 
     * @type {Array<LanguageEnum>}
     * @memberof ApiOverviewModel
     */
    languages?: Array<LanguageEnum> | null;
    /**
     * 
     * @type {boolean}
     * @memberof ApiOverviewModel
     */
    updateIndexes?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ApiOverviewModel
     */
    environment?: string | null;
}

/**
 * Check if a given object implements the ApiOverviewModel interface.
 */
export function instanceOfApiOverviewModel(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ApiOverviewModelFromJSON(json: any): ApiOverviewModel {
    return ApiOverviewModelFromJSONTyped(json, false);
}

export function ApiOverviewModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiOverviewModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'documentation': !exists(json, 'documentation') ? undefined : json['documentation'],
        'systemStatus': !exists(json, 'system_status') ? undefined : ApiOverviewModelStatusFromJSON(json['system_status']),
        'languages': !exists(json, 'languages') ? undefined : (json['languages'] === null ? null : (json['languages'] as Array<any>).map(LanguageEnumFromJSON)),
        'updateIndexes': !exists(json, 'update_indexes') ? undefined : json['update_indexes'],
        'environment': !exists(json, 'environment') ? undefined : json['environment'],
    };
}

export function ApiOverviewModelToJSON(value?: ApiOverviewModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'documentation': value.documentation,
        'system_status': ApiOverviewModelStatusToJSON(value.systemStatus),
        'languages': value.languages === undefined ? undefined : (value.languages === null ? null : (value.languages as Array<any>).map(LanguageEnumToJSON)),
        'update_indexes': value.updateIndexes,
        'environment': value.environment,
    };
}

