/* tslint:disable */
/* eslint-disable */
/**
 * BMM Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AppDownloadLinksQueryDownloadLinks
 */
export interface AppDownloadLinksQueryDownloadLinks {
    /**
     * 
     * @type {string}
     * @memberof AppDownloadLinksQueryDownloadLinks
     */
    windows?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AppDownloadLinksQueryDownloadLinks
     */
    macIntel?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AppDownloadLinksQueryDownloadLinks
     */
    macArm?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AppDownloadLinksQueryDownloadLinks
     */
    ios?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AppDownloadLinksQueryDownloadLinks
     */
    android?: string | null;
}

/**
 * Check if a given object implements the AppDownloadLinksQueryDownloadLinks interface.
 */
export function instanceOfAppDownloadLinksQueryDownloadLinks(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AppDownloadLinksQueryDownloadLinksFromJSON(json: any): AppDownloadLinksQueryDownloadLinks {
    return AppDownloadLinksQueryDownloadLinksFromJSONTyped(json, false);
}

export function AppDownloadLinksQueryDownloadLinksFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppDownloadLinksQueryDownloadLinks {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'windows': !exists(json, 'windows') ? undefined : json['windows'],
        'macIntel': !exists(json, 'mac_intel') ? undefined : json['mac_intel'],
        'macArm': !exists(json, 'mac_arm') ? undefined : json['mac_arm'],
        'ios': !exists(json, 'ios') ? undefined : json['ios'],
        'android': !exists(json, 'android') ? undefined : json['android'],
    };
}

export function AppDownloadLinksQueryDownloadLinksToJSON(value?: AppDownloadLinksQueryDownloadLinks | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'windows': value.windows,
        'mac_intel': value.macIntel,
        'mac_arm': value.macArm,
        'ios': value.ios,
        'android': value.android,
    };
}

