/* tslint:disable */
/* eslint-disable */
/**
 * BMM Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChapterHeader
 */
export interface ChapterHeader {
    /**
     * 
     * @type {string}
     * @memberof ChapterHeader
     */
    readonly type: ChapterHeaderTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof ChapterHeader
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof ChapterHeader
     */
    title?: string | null;
}


/**
 * @export
 */
export const ChapterHeaderTypeEnum = {
    ChapterHeader: 'chapter_header'
} as const;
export type ChapterHeaderTypeEnum = typeof ChapterHeaderTypeEnum[keyof typeof ChapterHeaderTypeEnum];


/**
 * Check if a given object implements the ChapterHeader interface.
 */
export function instanceOfChapterHeader(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function ChapterHeaderFromJSON(json: any): ChapterHeader {
    return ChapterHeaderFromJSONTyped(json, false);
}

export function ChapterHeaderFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChapterHeader {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
        'title': !exists(json, 'title') ? undefined : json['title'],
    };
}

export function ChapterHeaderToJSON(value?: ChapterHeader | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'title': value.title,
    };
}

