/* tslint:disable */
/* eslint-disable */
/**
 * BMM Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Church
 */
export interface Church {
    /**
     * 
     * @type {string}
     * @memberof Church
     */
    orgUid?: string;
    /**
     * 
     * @type {string}
     * @memberof Church
     */
    churchName?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Church
     */
    memberCount?: number;
    /**
     * 
     * @type {number}
     * @memberof Church
     */
    u12Count?: number;
    /**
     * 
     * @type {number}
     * @memberof Church
     */
    u18Count?: number;
    /**
     * 
     * @type {number}
     * @memberof Church
     */
    u24Count?: number;
    /**
     * 
     * @type {number}
     * @memberof Church
     */
    u30Count?: number;
    /**
     * 
     * @type {number}
     * @memberof Church
     */
    u36Count?: number;
    /**
     * 
     * @type {number}
     * @memberof Church
     */
    o36Count?: number;
    /**
     * 
     * @type {number}
     * @memberof Church
     */
    age13To17?: number;
    /**
     * 
     * @type {number}
     * @memberof Church
     */
    age18To25?: number;
    /**
     * 
     * @type {number}
     * @memberof Church
     */
    age19To25?: number;
    /**
     * 
     * @type {number}
     * @memberof Church
     */
    age26To35?: number;
    /**
     * 
     * @type {number}
     * @memberof Church
     */
    age36To50?: number;
    /**
     * 
     * @type {number}
     * @memberof Church
     */
    age51To99?: number;
}

/**
 * Check if a given object implements the Church interface.
 */
export function instanceOfChurch(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ChurchFromJSON(json: any): Church {
    return ChurchFromJSONTyped(json, false);
}

export function ChurchFromJSONTyped(json: any, ignoreDiscriminator: boolean): Church {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'orgUid': !exists(json, 'org_uid') ? undefined : json['org_uid'],
        'churchName': !exists(json, 'church_name') ? undefined : json['church_name'],
        'memberCount': !exists(json, 'member_count') ? undefined : json['member_count'],
        'u12Count': !exists(json, 'u12_count') ? undefined : json['u12_count'],
        'u18Count': !exists(json, 'u18_count') ? undefined : json['u18_count'],
        'u24Count': !exists(json, 'u24_count') ? undefined : json['u24_count'],
        'u30Count': !exists(json, 'u30_count') ? undefined : json['u30_count'],
        'u36Count': !exists(json, 'u36_count') ? undefined : json['u36_count'],
        'o36Count': !exists(json, 'o36_count') ? undefined : json['o36_count'],
        'age13To17': !exists(json, 'age13_to17') ? undefined : json['age13_to17'],
        'age18To25': !exists(json, 'age18_to25') ? undefined : json['age18_to25'],
        'age19To25': !exists(json, 'age19_to25') ? undefined : json['age19_to25'],
        'age26To35': !exists(json, 'age26_to35') ? undefined : json['age26_to35'],
        'age36To50': !exists(json, 'age36_to50') ? undefined : json['age36_to50'],
        'age51To99': !exists(json, 'age51_to99') ? undefined : json['age51_to99'],
    };
}

export function ChurchToJSON(value?: Church | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'org_uid': value.orgUid,
        'church_name': value.churchName,
        'member_count': value.memberCount,
        'u12_count': value.u12Count,
        'u18_count': value.u18Count,
        'u24_count': value.u24Count,
        'u30_count': value.u30Count,
        'u36_count': value.u36Count,
        'o36_count': value.o36Count,
        'age13_to17': value.age13To17,
        'age18_to25': value.age18To25,
        'age19_to25': value.age19To25,
        'age26_to35': value.age26To35,
        'age36_to50': value.age36To50,
        'age51_to99': value.age51To99,
    };
}

