/* tslint:disable */
/* eslint-disable */
/**
 * BMM Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const CurrentWeeksStreakVmHomeScreenTextOptions = {
    PerfectWeeks: 'PerfectWeeks',
    DaysInRow: 'DaysInRow'
} as const;
export type CurrentWeeksStreakVmHomeScreenTextOptions = typeof CurrentWeeksStreakVmHomeScreenTextOptions[keyof typeof CurrentWeeksStreakVmHomeScreenTextOptions];


export function CurrentWeeksStreakVmHomeScreenTextOptionsFromJSON(json: any): CurrentWeeksStreakVmHomeScreenTextOptions {
    return CurrentWeeksStreakVmHomeScreenTextOptionsFromJSONTyped(json, false);
}

export function CurrentWeeksStreakVmHomeScreenTextOptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CurrentWeeksStreakVmHomeScreenTextOptions {
    return json as CurrentWeeksStreakVmHomeScreenTextOptions;
}

export function CurrentWeeksStreakVmHomeScreenTextOptionsToJSON(value?: CurrentWeeksStreakVmHomeScreenTextOptions | null): any {
    return value as any;
}

