/* tslint:disable */
/* eslint-disable */
/**
 * BMM Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DiscoverResponse } from './DiscoverResponse';
import {
    DiscoverResponseFromJSON,
    DiscoverResponseFromJSONTyped,
    DiscoverResponseToJSON,
} from './DiscoverResponse';

/**
 * 
 * @export
 * @interface DocumentListPlaylist
 */
export interface DocumentListPlaylist {
    /**
     * 
     * @type {string}
     * @memberof DocumentListPlaylist
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DocumentListPlaylist
     */
    translationParent?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DocumentListPlaylist
     */
    translationId?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof DocumentListPlaylist
     */
    supportsPaging?: boolean;
    /**
     * 
     * @type {Array<DiscoverResponse>}
     * @memberof DocumentListPlaylist
     */
    items?: Array<DiscoverResponse> | null;
}

/**
 * Check if a given object implements the DocumentListPlaylist interface.
 */
export function instanceOfDocumentListPlaylist(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DocumentListPlaylistFromJSON(json: any): DocumentListPlaylist {
    return DocumentListPlaylistFromJSONTyped(json, false);
}

export function DocumentListPlaylistFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentListPlaylist {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': !exists(json, 'title') ? undefined : json['title'],
        'translationParent': !exists(json, 'translation_parent') ? undefined : json['translation_parent'],
        'translationId': !exists(json, 'translation_id') ? undefined : json['translation_id'],
        'supportsPaging': !exists(json, 'supports_paging') ? undefined : json['supports_paging'],
        'items': !exists(json, 'items') ? undefined : (json['items'] === null ? null : (json['items'] as Array<any>).map(DiscoverResponseFromJSON)),
    };
}

export function DocumentListPlaylistToJSON(value?: DocumentListPlaylist | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'translation_parent': value.translationParent,
        'translation_id': value.translationId,
        'supports_paging': value.supportsPaging,
        'items': value.items === undefined ? undefined : (value.items === null ? null : (value.items as Array<any>).map(DiscoverResponseToJSON)),
    };
}

