/* tslint:disable */
/* eslint-disable */
/**
 * BMM Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DocumentListAudiobooksItemsInner } from './DocumentListAudiobooksItemsInner';
import {
    DocumentListAudiobooksItemsInnerFromJSON,
    DocumentListAudiobooksItemsInnerFromJSONTyped,
    DocumentListAudiobooksItemsInnerToJSON,
} from './DocumentListAudiobooksItemsInner';

/**
 * 
 * @export
 * @interface DocumentListAudiobooks
 */
export interface DocumentListAudiobooks {
    /**
     * 
     * @type {string}
     * @memberof DocumentListAudiobooks
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DocumentListAudiobooks
     */
    translationParent?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DocumentListAudiobooks
     */
    translationId?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof DocumentListAudiobooks
     */
    supportsPaging?: boolean;
    /**
     * 
     * @type {Array<DocumentListAudiobooksItemsInner>}
     * @memberof DocumentListAudiobooks
     */
    items?: Array<DocumentListAudiobooksItemsInner> | null;
}

/**
 * Check if a given object implements the DocumentListAudiobooks interface.
 */
export function instanceOfDocumentListAudiobooks(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DocumentListAudiobooksFromJSON(json: any): DocumentListAudiobooks {
    return DocumentListAudiobooksFromJSONTyped(json, false);
}

export function DocumentListAudiobooksFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentListAudiobooks {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': !exists(json, 'title') ? undefined : json['title'],
        'translationParent': !exists(json, 'translation_parent') ? undefined : json['translation_parent'],
        'translationId': !exists(json, 'translation_id') ? undefined : json['translation_id'],
        'supportsPaging': !exists(json, 'supports_paging') ? undefined : json['supports_paging'],
        'items': !exists(json, 'items') ? undefined : (json['items'] === null ? null : (json['items'] as Array<any>).map(DocumentListAudiobooksItemsInnerFromJSON)),
    };
}

export function DocumentListAudiobooksToJSON(value?: DocumentListAudiobooks | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'translation_parent': value.translationParent,
        'translation_id': value.translationId,
        'supports_paging': value.supportsPaging,
        'items': value.items === undefined ? undefined : (value.items === null ? null : (value.items as Array<any>).map(DocumentListAudiobooksItemsInnerToJSON)),
    };
}

