/* tslint:disable */
/* eslint-disable */
/**
 * BMM Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AlbumModel } from './AlbumModel';
import {
    AlbumModelFromJSON,
    AlbumModelFromJSONTyped,
    AlbumModelToJSON,
} from './AlbumModel';

/**
 * 
 * @export
 * @interface DocumentListEvents
 */
export interface DocumentListEvents {
    /**
     * 
     * @type {string}
     * @memberof DocumentListEvents
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DocumentListEvents
     */
    translationParent?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DocumentListEvents
     */
    translationId?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof DocumentListEvents
     */
    supportsPaging?: boolean;
    /**
     * 
     * @type {Array<AlbumModel>}
     * @memberof DocumentListEvents
     */
    items?: Array<AlbumModel> | null;
}

/**
 * Check if a given object implements the DocumentListEvents interface.
 */
export function instanceOfDocumentListEvents(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DocumentListEventsFromJSON(json: any): DocumentListEvents {
    return DocumentListEventsFromJSONTyped(json, false);
}

export function DocumentListEventsFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentListEvents {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': !exists(json, 'title') ? undefined : json['title'],
        'translationParent': !exists(json, 'translation_parent') ? undefined : json['translation_parent'],
        'translationId': !exists(json, 'translation_id') ? undefined : json['translation_id'],
        'supportsPaging': !exists(json, 'supports_paging') ? undefined : json['supports_paging'],
        'items': !exists(json, 'items') ? undefined : (json['items'] === null ? null : (json['items'] as Array<any>).map(AlbumModelFromJSON)),
    };
}

export function DocumentListEventsToJSON(value?: DocumentListEvents | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'translation_parent': value.translationParent,
        'translation_id': value.translationId,
        'supports_paging': value.supportsPaging,
        'items': value.items === undefined ? undefined : (value.items === null ? null : (value.items as Array<any>).map(AlbumModelToJSON)),
    };
}

