/* tslint:disable */
/* eslint-disable */
/**
 * BMM Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PodcastModel } from './PodcastModel';
import {
    PodcastModelFromJSON,
    PodcastModelFromJSONTyped,
    PodcastModelToJSON,
} from './PodcastModel';

/**
 * 
 * @export
 * @interface DocumentListPodcastModel
 */
export interface DocumentListPodcastModel {
    /**
     * 
     * @type {string}
     * @memberof DocumentListPodcastModel
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DocumentListPodcastModel
     * @deprecated
     */
    translationParent?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DocumentListPodcastModel
     * @deprecated
     */
    translationId?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof DocumentListPodcastModel
     */
    supportsPaging?: boolean;
    /**
     * 
     * @type {Array<PodcastModel>}
     * @memberof DocumentListPodcastModel
     */
    items?: Array<PodcastModel> | null;
    /**
     * 
     * @type {number}
     * @memberof DocumentListPodcastModel
     */
    totalItems?: number;
}

/**
 * Check if a given object implements the DocumentListPodcastModel interface.
 */
export function instanceOfDocumentListPodcastModel(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DocumentListPodcastModelFromJSON(json: any): DocumentListPodcastModel {
    return DocumentListPodcastModelFromJSONTyped(json, false);
}

export function DocumentListPodcastModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentListPodcastModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': !exists(json, 'title') ? undefined : json['title'],
        'translationParent': !exists(json, 'translation_parent') ? undefined : json['translation_parent'],
        'translationId': !exists(json, 'translation_id') ? undefined : json['translation_id'],
        'supportsPaging': !exists(json, 'supports_paging') ? undefined : json['supports_paging'],
        'items': !exists(json, 'items') ? undefined : (json['items'] === null ? null : (json['items'] as Array<any>).map(PodcastModelFromJSON)),
        'totalItems': !exists(json, 'total_items') ? undefined : json['total_items'],
    };
}

export function DocumentListPodcastModelToJSON(value?: DocumentListPodcastModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'translation_parent': value.translationParent,
        'translation_id': value.translationId,
        'supports_paging': value.supportsPaging,
        'items': value.items === undefined ? undefined : (value.items === null ? null : (value.items as Array<any>).map(PodcastModelToJSON)),
        'total_items': value.totalItems,
    };
}

