/* tslint:disable */
/* eslint-disable */
/**
 * BMM Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { IDiscoverable } from './IDiscoverable';
import {
    IDiscoverableFromJSON,
    IDiscoverableFromJSONTyped,
    IDiscoverableToJSON,
} from './IDiscoverable';

/**
 * 
 * @export
 * @interface DocumentListIDiscoverable
 */
export interface DocumentListIDiscoverable {
    /**
     * 
     * @type {string}
     * @memberof DocumentListIDiscoverable
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DocumentListIDiscoverable
     */
    translationParent?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DocumentListIDiscoverable
     */
    translationId?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof DocumentListIDiscoverable
     */
    supportsPaging?: boolean;
    /**
     * 
     * @type {Array<IDiscoverable>}
     * @memberof DocumentListIDiscoverable
     */
    items?: Array<IDiscoverable> | null;
}

/**
 * Check if a given object implements the DocumentListIDiscoverable interface.
 */
export function instanceOfDocumentListIDiscoverable(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DocumentListIDiscoverableFromJSON(json: any): DocumentListIDiscoverable {
    return DocumentListIDiscoverableFromJSONTyped(json, false);
}

export function DocumentListIDiscoverableFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentListIDiscoverable {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': !exists(json, 'title') ? undefined : json['title'],
        'translationParent': !exists(json, 'translation_parent') ? undefined : json['translation_parent'],
        'translationId': !exists(json, 'translation_id') ? undefined : json['translation_id'],
        'supportsPaging': !exists(json, 'supports_paging') ? undefined : json['supports_paging'],
        'items': !exists(json, 'items') ? undefined : (json['items'] === null ? null : (json['items'] as Array<any>).map(IDiscoverableFromJSON)),
    };
}

export function DocumentListIDiscoverableToJSON(value?: DocumentListIDiscoverable | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'translation_parent': value.translationParent,
        'translation_id': value.translationId,
        'supports_paging': value.supportsPaging,
        'items': value.items === undefined ? undefined : (value.items === null ? null : (value.items as Array<any>).map(IDiscoverableToJSON)),
    };
}

