/* tslint:disable */
/* eslint-disable */
/**
 * BMM Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AchievementModel } from './AchievementModel';
import {
    AchievementModelFromJSON,
    AchievementModelFromJSONTyped,
    AchievementModelToJSON,
} from './AchievementModel';
import type { CurrentWeeksStreakVm } from './CurrentWeeksStreakVm';
import {
    CurrentWeeksStreakVmFromJSON,
    CurrentWeeksStreakVmFromJSONTyped,
    CurrentWeeksStreakVmToJSON,
} from './CurrentWeeksStreakVm';

/**
 * 
 * @export
 * @interface ForbildePoints
 */
export interface ForbildePoints {
    /**
     * 
     * @type {CurrentWeeksStreakVm}
     * @memberof ForbildePoints
     */
    streak?: CurrentWeeksStreakVm;
    /**
     * 
     * @type {number}
     * @memberof ForbildePoints
     */
    days?: number;
    /**
     * 
     * @type {number}
     * @memberof ForbildePoints
     */
    currentBoost?: number;
    /**
     * 
     * @type {number}
     * @memberof ForbildePoints
     */
    points?: number;
    /**
     * 
     * @type {Array<AchievementModel>}
     * @memberof ForbildePoints
     */
    achievements?: Array<AchievementModel> | null;
}

/**
 * Check if a given object implements the ForbildePoints interface.
 */
export function instanceOfForbildePoints(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ForbildePointsFromJSON(json: any): ForbildePoints {
    return ForbildePointsFromJSONTyped(json, false);
}

export function ForbildePointsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ForbildePoints {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'streak': !exists(json, 'streak') ? undefined : CurrentWeeksStreakVmFromJSON(json['streak']),
        'days': !exists(json, 'days') ? undefined : json['days'],
        'currentBoost': !exists(json, 'current_boost') ? undefined : json['current_boost'],
        'points': !exists(json, 'points') ? undefined : json['points'],
        'achievements': !exists(json, 'achievements') ? undefined : (json['achievements'] === null ? null : (json['achievements'] as Array<any>).map(AchievementModelFromJSON)),
    };
}

export function ForbildePointsToJSON(value?: ForbildePoints | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'streak': CurrentWeeksStreakVmToJSON(value.streak),
        'days': value.days,
        'current_boost': value.currentBoost,
        'points': value.points,
        'achievements': value.achievements === undefined ? undefined : (value.achievements === null ? null : (value.achievements as Array<any>).map(AchievementModelToJSON)),
    };
}

