/* tslint:disable */
/* eslint-disable */
/**
 * BMM Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PersonGenderEnum } from './PersonGenderEnum';
import {
    PersonGenderEnumFromJSON,
    PersonGenderEnumFromJSONTyped,
    PersonGenderEnumToJSON,
} from './PersonGenderEnum';

/**
 * 
 * @export
 * @interface FraKaareDrawCommand
 */
export interface FraKaareDrawCommand {
    /**
     * 
     * @type {string}
     * @memberof FraKaareDrawCommand
     */
    drawOptionId?: string | null;
    /**
     * 
     * @type {number}
     * @memberof FraKaareDrawCommand
     */
    earliestBirthYear?: number;
    /**
     * 
     * @type {number}
     * @memberof FraKaareDrawCommand
     */
    latestBirthYear?: number;
    /**
     * 
     * @type {string}
     * @memberof FraKaareDrawCommand
     */
    churchUid?: string | null;
    /**
     * 
     * @type {PersonGenderEnum}
     * @memberof FraKaareDrawCommand
     */
    gender?: PersonGenderEnum;
}

/**
 * Check if a given object implements the FraKaareDrawCommand interface.
 */
export function instanceOfFraKaareDrawCommand(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function FraKaareDrawCommandFromJSON(json: any): FraKaareDrawCommand {
    return FraKaareDrawCommandFromJSONTyped(json, false);
}

export function FraKaareDrawCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): FraKaareDrawCommand {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'drawOptionId': !exists(json, 'draw_option_id') ? undefined : json['draw_option_id'],
        'earliestBirthYear': !exists(json, 'earliest_birth_year') ? undefined : json['earliest_birth_year'],
        'latestBirthYear': !exists(json, 'latest_birth_year') ? undefined : json['latest_birth_year'],
        'churchUid': !exists(json, 'church_uid') ? undefined : json['church_uid'],
        'gender': !exists(json, 'gender') ? undefined : PersonGenderEnumFromJSON(json['gender']),
    };
}

export function FraKaareDrawCommandToJSON(value?: FraKaareDrawCommand | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'draw_option_id': value.drawOptionId,
        'earliest_birth_year': value.earliestBirthYear,
        'latest_birth_year': value.latestBirthYear,
        'church_uid': value.churchUid,
        'gender': PersonGenderEnumToJSON(value.gender),
    };
}

