/* tslint:disable */
/* eslint-disable */
/**
 * BMM Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FraKaareDrawCommandDrawOption
 */
export interface FraKaareDrawCommandDrawOption {
    /**
     * 
     * @type {string}
     * @memberof FraKaareDrawCommandDrawOption
     */
    id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FraKaareDrawCommandDrawOption
     */
    description?: string | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof FraKaareDrawCommandDrawOption
     */
    trackIds?: Array<number> | null;
}

/**
 * Check if a given object implements the FraKaareDrawCommandDrawOption interface.
 */
export function instanceOfFraKaareDrawCommandDrawOption(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function FraKaareDrawCommandDrawOptionFromJSON(json: any): FraKaareDrawCommandDrawOption {
    return FraKaareDrawCommandDrawOptionFromJSONTyped(json, false);
}

export function FraKaareDrawCommandDrawOptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): FraKaareDrawCommandDrawOption {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'trackIds': !exists(json, 'track_ids') ? undefined : json['track_ids'],
    };
}

export function FraKaareDrawCommandDrawOptionToJSON(value?: FraKaareDrawCommandDrawOption | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'description': value.description,
        'track_ids': value.trackIds,
    };
}

