/* tslint:disable */
/* eslint-disable */
/**
 * BMM Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PersonGenderEnum } from './PersonGenderEnum';
import {
    PersonGenderEnumFromJSON,
    PersonGenderEnumFromJSONTyped,
    PersonGenderEnumToJSON,
} from './PersonGenderEnum';

/**
 * 
 * @export
 * @interface FraKaareDrawCommandResponse
 */
export interface FraKaareDrawCommandResponse {
    /**
     * 
     * @type {string}
     * @memberof FraKaareDrawCommandResponse
     */
    winnerDisplayName?: string | null;
    /**
     * 
     * @type {PersonGenderEnum}
     * @memberof FraKaareDrawCommandResponse
     */
    winnerGender?: PersonGenderEnum;
    /**
     * 
     * @type {number}
     * @memberof FraKaareDrawCommandResponse
     */
    winnerBirthYear?: number;
}

/**
 * Check if a given object implements the FraKaareDrawCommandResponse interface.
 */
export function instanceOfFraKaareDrawCommandResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function FraKaareDrawCommandResponseFromJSON(json: any): FraKaareDrawCommandResponse {
    return FraKaareDrawCommandResponseFromJSONTyped(json, false);
}

export function FraKaareDrawCommandResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FraKaareDrawCommandResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'winnerDisplayName': !exists(json, 'winner_display_name') ? undefined : json['winner_display_name'],
        'winnerGender': !exists(json, 'winner_gender') ? undefined : PersonGenderEnumFromJSON(json['winner_gender']),
        'winnerBirthYear': !exists(json, 'winner_birth_year') ? undefined : json['winner_birth_year'],
    };
}

export function FraKaareDrawCommandResponseToJSON(value?: FraKaareDrawCommandResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'winner_display_name': value.winnerDisplayName,
        'winner_gender': PersonGenderEnumToJSON(value.winnerGender),
        'winner_birth_year': value.winnerBirthYear,
    };
}

