/* tslint:disable */
/* eslint-disable */
/**
 * BMM Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GetFraKaareStatisticsChurchStatistics } from './GetFraKaareStatisticsChurchStatistics';
import {
    GetFraKaareStatisticsChurchStatisticsFromJSON,
    GetFraKaareStatisticsChurchStatisticsFromJSONTyped,
    GetFraKaareStatisticsChurchStatisticsToJSON,
} from './GetFraKaareStatisticsChurchStatistics';

/**
 * 
 * @export
 * @interface GetFraKaareStatisticsResponse
 */
export interface GetFraKaareStatisticsResponse {
    /**
     * 
     * @type {string}
     * @memberof GetFraKaareStatisticsResponse
     */
    highlightedChurchName?: string | null;
    /**
     * 
     * @type {Array<GetFraKaareStatisticsChurchStatistics>}
     * @memberof GetFraKaareStatisticsResponse
     */
    largeChurches?: Array<GetFraKaareStatisticsChurchStatistics> | null;
    /**
     * 
     * @type {Array<GetFraKaareStatisticsChurchStatistics>}
     * @memberof GetFraKaareStatisticsResponse
     */
    smallChurches?: Array<GetFraKaareStatisticsChurchStatistics> | null;
}

/**
 * Check if a given object implements the GetFraKaareStatisticsResponse interface.
 */
export function instanceOfGetFraKaareStatisticsResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetFraKaareStatisticsResponseFromJSON(json: any): GetFraKaareStatisticsResponse {
    return GetFraKaareStatisticsResponseFromJSONTyped(json, false);
}

export function GetFraKaareStatisticsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetFraKaareStatisticsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'highlightedChurchName': !exists(json, 'highlighted_church_name') ? undefined : json['highlighted_church_name'],
        'largeChurches': !exists(json, 'large_churches') ? undefined : (json['large_churches'] === null ? null : (json['large_churches'] as Array<any>).map(GetFraKaareStatisticsChurchStatisticsFromJSON)),
        'smallChurches': !exists(json, 'small_churches') ? undefined : (json['small_churches'] === null ? null : (json['small_churches'] as Array<any>).map(GetFraKaareStatisticsChurchStatisticsFromJSON)),
    };
}

export function GetFraKaareStatisticsResponseToJSON(value?: GetFraKaareStatisticsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'highlighted_church_name': value.highlightedChurchName,
        'large_churches': value.largeChurches === undefined ? undefined : (value.largeChurches === null ? null : (value.largeChurches as Array<any>).map(GetFraKaareStatisticsChurchStatisticsToJSON)),
        'small_churches': value.smallChurches === undefined ? undefined : (value.smallChurches === null ? null : (value.smallChurches as Array<any>).map(GetFraKaareStatisticsChurchStatisticsToJSON)),
    };
}

