/* tslint:disable */
/* eslint-disable */
/**
 * BMM Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetFraKaareStatisticsChurchStatisticsSnapshot
 */
export interface GetFraKaareStatisticsChurchStatisticsSnapshot {
    /**
     * 
     * @type {Date}
     * @memberof GetFraKaareStatisticsChurchStatisticsSnapshot
     */
    snapshotDate?: Date;
    /**
     * 
     * @type {number}
     * @memberof GetFraKaareStatisticsChurchStatisticsSnapshot
     */
    oneEpisodePercentAverage?: number;
    /**
     * 
     * @type {number}
     * @memberof GetFraKaareStatisticsChurchStatisticsSnapshot
     */
    allEpisodesPercentAverage?: number;
}

/**
 * Check if a given object implements the GetFraKaareStatisticsChurchStatisticsSnapshot interface.
 */
export function instanceOfGetFraKaareStatisticsChurchStatisticsSnapshot(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetFraKaareStatisticsChurchStatisticsSnapshotFromJSON(json: any): GetFraKaareStatisticsChurchStatisticsSnapshot {
    return GetFraKaareStatisticsChurchStatisticsSnapshotFromJSONTyped(json, false);
}

export function GetFraKaareStatisticsChurchStatisticsSnapshotFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetFraKaareStatisticsChurchStatisticsSnapshot {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'snapshotDate': !exists(json, 'snapshot_date') ? undefined : (new Date(json['snapshot_date'])),
        'oneEpisodePercentAverage': !exists(json, 'one_episode_percent_average') ? undefined : json['one_episode_percent_average'],
        'allEpisodesPercentAverage': !exists(json, 'all_episodes_percent_average') ? undefined : json['all_episodes_percent_average'],
    };
}

export function GetFraKaareStatisticsChurchStatisticsSnapshotToJSON(value?: GetFraKaareStatisticsChurchStatisticsSnapshot | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'snapshot_date': value.snapshotDate === undefined ? undefined : (value.snapshotDate.toISOString()),
        'one_episode_percent_average': value.oneEpisodePercentAverage,
        'all_episodes_percent_average': value.allEpisodesPercentAverage,
    };
}

