/* tslint:disable */
/* eslint-disable */
/**
 * BMM Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetFraKaareStatisticsChurch
 */
export interface GetFraKaareStatisticsChurch {
    /**
     * 
     * @type {string}
     * @memberof GetFraKaareStatisticsChurch
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof GetFraKaareStatisticsChurch
     */
    name?: string | null;
}

/**
 * Check if a given object implements the GetFraKaareStatisticsChurch interface.
 */
export function instanceOfGetFraKaareStatisticsChurch(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetFraKaareStatisticsChurchFromJSON(json: any): GetFraKaareStatisticsChurch {
    return GetFraKaareStatisticsChurchFromJSONTyped(json, false);
}

export function GetFraKaareStatisticsChurchFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetFraKaareStatisticsChurch {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function GetFraKaareStatisticsChurchToJSON(value?: GetFraKaareStatisticsChurch | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
    };
}

