/* tslint:disable */
/* eslint-disable */
/**
 * BMM Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GroupGoalModelTrackReference
 */
export interface GroupGoalModelTrackReference {
    /**
     * 
     * @type {Date}
     * @memberof GroupGoalModelTrackReference
     */
    date?: Date;
    /**
     * 
     * @type {number}
     * @memberof GroupGoalModelTrackReference
     */
    trackId?: number;
}

/**
 * Check if a given object implements the GroupGoalModelTrackReference interface.
 */
export function instanceOfGroupGoalModelTrackReference(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GroupGoalModelTrackReferenceFromJSON(json: any): GroupGoalModelTrackReference {
    return GroupGoalModelTrackReferenceFromJSONTyped(json, false);
}

export function GroupGoalModelTrackReferenceFromJSONTyped(json: any, ignoreDiscriminator: boolean): GroupGoalModelTrackReference {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'date': !exists(json, 'date') ? undefined : (new Date(json['date'])),
        'trackId': !exists(json, 'trackId') ? undefined : json['trackId'],
    };
}

export function GroupGoalModelTrackReferenceToJSON(value?: GroupGoalModelTrackReference | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'date': value.date === undefined ? undefined : (value.date.toISOString()),
        'trackId': value.trackId,
    };
}

