/* tslint:disable */
/* eslint-disable */
/**
 * BMM Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GroupGoalModelTrackReference } from './GroupGoalModelTrackReference';
import {
    GroupGoalModelTrackReferenceFromJSON,
    GroupGoalModelTrackReferenceFromJSONTyped,
    GroupGoalModelTrackReferenceToJSON,
} from './GroupGoalModelTrackReference';

/**
 * 
 * @export
 * @interface GroupGoalModel
 */
export interface GroupGoalModel {
    /**
     * 
     * @type {string}
     * @memberof GroupGoalModel
     */
    ownerName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GroupGoalModel
     */
    name?: string | null;
    /**
     * 
     * @type {number}
     * @memberof GroupGoalModel
     */
    participants?: number;
    /**
     * 
     * @type {number}
     * @memberof GroupGoalModel
     */
    tracks?: number;
    /**
     * 
     * @type {Date}
     * @memberof GroupGoalModel
     */
    start?: Date;
    /**
     * 
     * @type {Date}
     * @memberof GroupGoalModel
     */
    end?: Date;
    /**
     * 
     * @type {boolean}
     * @memberof GroupGoalModel
     */
    joined?: boolean;
    /**
     * 
     * @type {number}
     * @memberof GroupGoalModel
     */
    percentOnTrack?: number;
    /**
     * 
     * @type {number}
     * @memberof GroupGoalModel
     */
    percentCaughtUp?: number;
    /**
     * 
     * @type {string}
     * @memberof GroupGoalModel
     */
    currentTrackTitle?: string | null;
    /**
     * 
     * @type {Array<GroupGoalModelTrackReference>}
     * @memberof GroupGoalModel
     */
    trackList?: Array<GroupGoalModelTrackReference> | null;
    /**
     * 
     * @type {number}
     * @memberof GroupGoalModel
     */
    percentListenedLatest?: number;
    /**
     * 
     * @type {number}
     * @memberof GroupGoalModel
     */
    collectiveEpisodes?: number;
}

/**
 * Check if a given object implements the GroupGoalModel interface.
 */
export function instanceOfGroupGoalModel(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GroupGoalModelFromJSON(json: any): GroupGoalModel {
    return GroupGoalModelFromJSONTyped(json, false);
}

export function GroupGoalModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): GroupGoalModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ownerName': !exists(json, 'owner_name') ? undefined : json['owner_name'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'participants': !exists(json, 'participants') ? undefined : json['participants'],
        'tracks': !exists(json, 'tracks') ? undefined : json['tracks'],
        'start': !exists(json, 'start') ? undefined : (new Date(json['start'])),
        'end': !exists(json, 'end') ? undefined : (new Date(json['end'])),
        'joined': !exists(json, 'joined') ? undefined : json['joined'],
        'percentOnTrack': !exists(json, 'percent_on_track') ? undefined : json['percent_on_track'],
        'percentCaughtUp': !exists(json, 'percent_caught_up') ? undefined : json['percent_caught_up'],
        'currentTrackTitle': !exists(json, 'current_track_title') ? undefined : json['current_track_title'],
        'trackList': !exists(json, 'track_list') ? undefined : (json['track_list'] === null ? null : (json['track_list'] as Array<any>).map(GroupGoalModelTrackReferenceFromJSON)),
        'percentListenedLatest': !exists(json, 'percent_listened_latest') ? undefined : json['percent_listened_latest'],
        'collectiveEpisodes': !exists(json, 'collective_episodes') ? undefined : json['collective_episodes'],
    };
}

export function GroupGoalModelToJSON(value?: GroupGoalModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'owner_name': value.ownerName,
        'name': value.name,
        'participants': value.participants,
        'tracks': value.tracks,
        'start': value.start === undefined ? undefined : (value.start.toISOString()),
        'end': value.end === undefined ? undefined : (value.end.toISOString()),
        'joined': value.joined,
        'percent_on_track': value.percentOnTrack,
        'percent_caught_up': value.percentCaughtUp,
        'current_track_title': value.currentTrackTitle,
        'track_list': value.trackList === undefined ? undefined : (value.trackList === null ? null : (value.trackList as Array<any>).map(GroupGoalModelTrackReferenceToJSON)),
        'percent_listened_latest': value.percentListenedLatest,
        'collective_episodes': value.collectiveEpisodes,
    };
}

