/* tslint:disable */
/* eslint-disable */
/**
 * BMM Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HvheControllerHvheStatus
 */
export interface HvheControllerHvheStatus {
    /**
     * 
     * @type {number}
     * @memberof HvheControllerHvheStatus
     */
    boys?: number;
    /**
     * 
     * @type {number}
     * @memberof HvheControllerHvheStatus
     */
    girls?: number;
}

/**
 * Check if a given object implements the HvheControllerHvheStatus interface.
 */
export function instanceOfHvheControllerHvheStatus(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function HvheControllerHvheStatusFromJSON(json: any): HvheControllerHvheStatus {
    return HvheControllerHvheStatusFromJSONTyped(json, false);
}

export function HvheControllerHvheStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): HvheControllerHvheStatus {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'boys': !exists(json, 'boys') ? undefined : json['boys'],
        'girls': !exists(json, 'girls') ? undefined : json['girls'],
    };
}

export function HvheControllerHvheStatusToJSON(value?: HvheControllerHvheStatus | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'boys': value.boys,
        'girls': value.girls,
    };
}

