/* tslint:disable */
/* eslint-disable */
/**
 * BMM Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    AlbumModel,
    instanceOfAlbumModel,
    AlbumModelFromJSON,
    AlbumModelFromJSONTyped,
    AlbumModelToJSON,
} from './AlbumModel';
import {
    ChapterHeader,
    instanceOfChapterHeader,
    ChapterHeaderFromJSON,
    ChapterHeaderFromJSONTyped,
    ChapterHeaderToJSON,
} from './ChapterHeader';

/**
 * @type IAlbumOrChapterHeader
 * 
 * @export
 */
export type IAlbumOrChapterHeader = { type: 'album' } & AlbumModel | { type: 'chapter_header' } & ChapterHeader;

export function IAlbumOrChapterHeaderFromJSON(json: any): IAlbumOrChapterHeader {
    return IAlbumOrChapterHeaderFromJSONTyped(json, false);
}

export function IAlbumOrChapterHeaderFromJSONTyped(json: any, ignoreDiscriminator: boolean): IAlbumOrChapterHeader {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    switch (json['type']) {
        case 'album':
            return {...AlbumModelFromJSONTyped(json, true), type: 'album'};
        case 'chapter_header':
            return {...ChapterHeaderFromJSONTyped(json, true), type: 'chapter_header'};
        default:
            throw new Error(`No variant of IAlbumOrChapterHeader exists with 'type=${json['type']}'`);
    }
}

export function IAlbumOrChapterHeaderToJSON(value?: IAlbumOrChapterHeader | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    switch (value['type']) {
        case 'album':
            return AlbumModelToJSON(value);
        case 'chapter_header':
            return ChapterHeaderToJSON(value);
        default:
            throw new Error(`No variant of IAlbumOrChapterHeader exists with 'type=${value['type']}'`);
    }

}

