/* tslint:disable */
/* eslint-disable */
/**
 * BMM Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { AlbumModel } from './AlbumModel';
import {
    instanceOfAlbumModel,
    AlbumModelFromJSON,
    AlbumModelFromJSONTyped,
    AlbumModelToJSON,
} from './AlbumModel';
import type { ChapterHeader } from './ChapterHeader';
import {
    instanceOfChapterHeader,
    ChapterHeaderFromJSON,
    ChapterHeaderFromJSONTyped,
    ChapterHeaderToJSON,
} from './ChapterHeader';
import type { PlaylistModel } from './PlaylistModel';
import {
    instanceOfPlaylistModel,
    PlaylistModelFromJSON,
    PlaylistModelFromJSONTyped,
    PlaylistModelToJSON,
} from './PlaylistModel';

/**
 * @type IAlbumPlaylistOrChapterHeader
 * 
 * @export
 */
export type IAlbumPlaylistOrChapterHeader = { type: 'album' } & AlbumModel | { type: 'chapter_header' } & ChapterHeader | { type: 'playlist' } & PlaylistModel;

export function IAlbumPlaylistOrChapterHeaderFromJSON(json: any): IAlbumPlaylistOrChapterHeader {
    return IAlbumPlaylistOrChapterHeaderFromJSONTyped(json, false);
}

export function IAlbumPlaylistOrChapterHeaderFromJSONTyped(json: any, ignoreDiscriminator: boolean): IAlbumPlaylistOrChapterHeader {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    switch (json['type']) {
        case 'album':
            return {...AlbumModelFromJSONTyped(json, true), type: 'album'};
        case 'chapter_header':
            return {...ChapterHeaderFromJSONTyped(json, true), type: 'chapter_header'};
        case 'playlist':
            return {...PlaylistModelFromJSONTyped(json, true), type: 'playlist'};
        default:
            throw new Error(`No variant of IAlbumPlaylistOrChapterHeader exists with 'type=${json['type']}'`);
    }
}

export function IAlbumPlaylistOrChapterHeaderToJSON(value?: IAlbumPlaylistOrChapterHeader | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    switch (value['type']) {
        case 'album':
            return AlbumModelToJSON(value);
        case 'chapter_header':
            return ChapterHeaderToJSON(value);
        case 'playlist':
            return PlaylistModelToJSON(value);
        default:
            throw new Error(`No variant of IAlbumPlaylistOrChapterHeader exists with 'type=${value['type']}'`);
    }

}

