/* tslint:disable */
/* eslint-disable */
/**
 * BMM Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    AlbumModel,
    instanceOfAlbumModel,
    AlbumModelFromJSON,
    AlbumModelFromJSONTyped,
    AlbumModelToJSON,
} from './AlbumModel';
import {
    PlaylistModel,
    instanceOfPlaylistModel,
    PlaylistModelFromJSON,
    PlaylistModelFromJSONTyped,
    PlaylistModelToJSON,
} from './PlaylistModel';
import {
    PodcastModel,
    instanceOfPodcastModel,
    PodcastModelFromJSON,
    PodcastModelFromJSONTyped,
    PodcastModelToJSON,
} from './PodcastModel';
import {
    SectionHeaderModel,
    instanceOfSectionHeaderModel,
    SectionHeaderModelFromJSON,
    SectionHeaderModelFromJSONTyped,
    SectionHeaderModelToJSON,
} from './SectionHeaderModel';

/**
 * @type IAlbumPodcastPlaylistOrSectionHeader
 * 
 * @export
 */
export type IAlbumPodcastPlaylistOrSectionHeader = { type: 'album' } & AlbumModel | { type: 'playlist' } & PlaylistModel | { type: 'podcast' } & PodcastModel | { type: 'section_header' } & SectionHeaderModel;

export function IAlbumPodcastPlaylistOrSectionHeaderFromJSON(json: any): IAlbumPodcastPlaylistOrSectionHeader {
    return IAlbumPodcastPlaylistOrSectionHeaderFromJSONTyped(json, false);
}

export function IAlbumPodcastPlaylistOrSectionHeaderFromJSONTyped(json: any, ignoreDiscriminator: boolean): IAlbumPodcastPlaylistOrSectionHeader {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    switch (json['type']) {
        case 'album':
            return {...AlbumModelFromJSONTyped(json, true), type: 'album'};
        case 'playlist':
            return {...PlaylistModelFromJSONTyped(json, true), type: 'playlist'};
        case 'podcast':
            return {...PodcastModelFromJSONTyped(json, true), type: 'podcast'};
        case 'section_header':
            return {...SectionHeaderModelFromJSONTyped(json, true), type: 'section_header'};
        default:
            throw new Error(`No variant of IAlbumPodcastPlaylistOrSectionHeader exists with 'type=${json['type']}'`);
    }
}

export function IAlbumPodcastPlaylistOrSectionHeaderToJSON(value?: IAlbumPodcastPlaylistOrSectionHeader | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    switch (value['type']) {
        case 'album':
            return AlbumModelToJSON(value);
        case 'playlist':
            return PlaylistModelToJSON(value);
        case 'podcast':
            return PodcastModelToJSON(value);
        case 'section_header':
            return SectionHeaderModelToJSON(value);
        default:
            throw new Error(`No variant of IAlbumPodcastPlaylistOrSectionHeader exists with 'type=${value['type']}'`);
    }

}

