/* tslint:disable */
/* eslint-disable */
/**
 * BMM Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IDocumentModel
 */
export interface IDocumentModel {
    /**
     * 
     * @type {number}
     * @memberof IDocumentModel
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof IDocumentModel
     */
    readonly type?: string | null;
}

/**
 * Check if a given object implements the IDocumentModel interface.
 */
export function instanceOfIDocumentModel(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function IDocumentModelFromJSON(json: any): IDocumentModel {
    return IDocumentModelFromJSONTyped(json, false);
}

export function IDocumentModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): IDocumentModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'type': !exists(json, 'type') ? undefined : json['type'],
    };
}

export function IDocumentModelToJSON(value?: IDocumentModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
    };
}

