/* tslint:disable */
/* eslint-disable */
/**
 * BMM Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const MediaTypeEnum = {
    Audio: 'audio',
    Video: 'video'
} as const;
export type MediaTypeEnum = typeof MediaTypeEnum[keyof typeof MediaTypeEnum];


export function MediaTypeEnumFromJSON(json: any): MediaTypeEnum {
    return MediaTypeEnumFromJSONTyped(json, false);
}

export function MediaTypeEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): MediaTypeEnum {
    return json as MediaTypeEnum;
}

export function MediaTypeEnumToJSON(value?: MediaTypeEnum | null): any {
    return value as any;
}

