/* tslint:disable */
/* eslint-disable */
/**
 * BMM Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { LanguageEnum } from './LanguageEnum';
import {
    LanguageEnumFromJSON,
    LanguageEnumFromJSONTyped,
    LanguageEnumToJSON,
} from './LanguageEnum';

/**
 * 
 * @export
 * @interface PlaylistPlaylistTranslation
 */
export interface PlaylistPlaylistTranslation {
    /**
     * 
     * @type {LanguageEnum}
     * @memberof PlaylistPlaylistTranslation
     */
    language?: LanguageEnum;
    /**
     * 
     * @type {string}
     * @memberof PlaylistPlaylistTranslation
     */
    title?: string | null;
}

/**
 * Check if a given object implements the PlaylistPlaylistTranslation interface.
 */
export function instanceOfPlaylistPlaylistTranslation(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PlaylistPlaylistTranslationFromJSON(json: any): PlaylistPlaylistTranslation {
    return PlaylistPlaylistTranslationFromJSONTyped(json, false);
}

export function PlaylistPlaylistTranslationFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlaylistPlaylistTranslation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'language': !exists(json, 'language') ? undefined : LanguageEnumFromJSON(json['language']),
        'title': !exists(json, 'title') ? undefined : json['title'],
    };
}

export function PlaylistPlaylistTranslationToJSON(value?: PlaylistPlaylistTranslation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'language': LanguageEnumToJSON(value.language),
        'title': value.title,
    };
}

