/* tslint:disable */
/* eslint-disable */
/**
 * BMM Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TrackListReference } from './TrackListReference';
import {
    TrackListReferenceFromJSON,
    TrackListReferenceFromJSONTyped,
    TrackListReferenceToJSON,
} from './TrackListReference';

/**
 * 
 * @export
 * @interface PodcastCollection
 */
export interface PodcastCollection {
    /**
     * 
     * @type {Array<TrackListReference>}
     * @memberof PodcastCollection
     */
    podcastReferences?: Array<TrackListReference> | null;
    /**
     * 
     * @type {Array<TrackListReference>}
     * @memberof PodcastCollection
     */
    readonly references?: Array<TrackListReference> | null;
}

/**
 * Check if a given object implements the PodcastCollection interface.
 */
export function instanceOfPodcastCollection(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PodcastCollectionFromJSON(json: any): PodcastCollection {
    return PodcastCollectionFromJSONTyped(json, false);
}

export function PodcastCollectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): PodcastCollection {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'podcastReferences': !exists(json, 'podcastReferences') ? undefined : (json['podcastReferences'] === null ? null : (json['podcastReferences'] as Array<any>).map(TrackListReferenceFromJSON)),
        'references': !exists(json, 'references') ? undefined : (json['references'] === null ? null : (json['references'] as Array<any>).map(TrackListReferenceFromJSON)),
    };
}

export function PodcastCollectionToJSON(value?: PodcastCollection | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'podcastReferences': value.podcastReferences === undefined ? undefined : (value.podcastReferences === null ? null : (value.podcastReferences as Array<any>).map(TrackListReferenceToJSON)),
    };
}

