/* tslint:disable */
/* eslint-disable */
/**
 * BMM Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { LanguageEnum } from './LanguageEnum';
import {
    LanguageEnumFromJSON,
    LanguageEnumFromJSONTyped,
    LanguageEnumToJSON,
} from './LanguageEnum';

/**
 * 
 * @export
 * @interface PodcastModel
 */
export interface PodcastModel {
    /**
     * 
     * @type {string}
     * @memberof PodcastModel
     */
    cover?: string | null;
    /**
     * 
     * @type {number}
     * @memberof PodcastModel
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof PodcastModel
     */
    readonly type?: string | null;
    /**
     * 
     * @type {Array<LanguageEnum>}
     * @memberof PodcastModel
     */
    languages?: Array<LanguageEnum> | null;
    /**
     * 
     * @type {LanguageEnum}
     * @memberof PodcastModel
     */
    language?: LanguageEnum;
    /**
     * 
     * @type {string}
     * @memberof PodcastModel
     */
    title?: string | null;
}

/**
 * Check if a given object implements the PodcastModel interface.
 */
export function instanceOfPodcastModel(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PodcastModelFromJSON(json: any): PodcastModel {
    return PodcastModelFromJSONTyped(json, false);
}

export function PodcastModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): PodcastModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'cover': !exists(json, 'cover') ? undefined : json['cover'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'type': !exists(json, 'type') ? undefined : json['type'],
        'languages': !exists(json, 'languages') ? undefined : (json['languages'] === null ? null : (json['languages'] as Array<any>).map(LanguageEnumFromJSON)),
        'language': !exists(json, 'language') ? undefined : LanguageEnumFromJSON(json['language']),
        'title': !exists(json, 'title') ? undefined : json['title'],
    };
}

export function PodcastModelToJSON(value?: PodcastModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'cover': value.cover,
        'id': value.id,
        'languages': value.languages === undefined ? undefined : (value.languages === null ? null : (value.languages as Array<any>).map(LanguageEnumToJSON)),
        'language': LanguageEnumToJSON(value.language),
        'title': value.title,
    };
}

