/* tslint:disable */
/* eslint-disable */
/**
 * BMM Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PodcastPQuery } from './PodcastPQuery';
import {
    PodcastPQueryFromJSON,
    PodcastPQueryFromJSONTyped,
    PodcastPQueryToJSON,
} from './PodcastPQuery';
import type { PodcastPodcastTranslation } from './PodcastPodcastTranslation';
import {
    PodcastPodcastTranslationFromJSON,
    PodcastPodcastTranslationFromJSONTyped,
    PodcastPodcastTranslationToJSON,
} from './PodcastPodcastTranslation';

/**
 * 
 * @export
 * @interface Podcast
 */
export interface Podcast {
    /**
     * 
     * @type {string}
     * @memberof Podcast
     */
    readonly type?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Podcast
     */
    cover?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Podcast
     */
    id?: number;
    /**
     * 
     * @type {Date}
     * @memberof Podcast
     */
    modifiedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Podcast
     */
    createdAt?: Date;
    /**
     * 
     * @type {PodcastPQuery}
     * @memberof Podcast
     */
    query?: PodcastPQuery;
    /**
     * 
     * @type {Array<PodcastPodcastTranslation>}
     * @memberof Podcast
     */
    translations?: Array<PodcastPodcastTranslation> | null;
}

/**
 * Check if a given object implements the Podcast interface.
 */
export function instanceOfPodcast(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PodcastFromJSON(json: any): Podcast {
    return PodcastFromJSONTyped(json, false);
}

export function PodcastFromJSONTyped(json: any, ignoreDiscriminator: boolean): Podcast {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': !exists(json, 'type') ? undefined : json['type'],
        'cover': !exists(json, 'cover') ? undefined : json['cover'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'modifiedAt': !exists(json, 'modified_at') ? undefined : (new Date(json['modified_at'])),
        'createdAt': !exists(json, 'created_at') ? undefined : (new Date(json['created_at'])),
        'query': !exists(json, 'query') ? undefined : PodcastPQueryFromJSON(json['query']),
        'translations': !exists(json, 'translations') ? undefined : (json['translations'] === null ? null : (json['translations'] as Array<any>).map(PodcastPodcastTranslationFromJSON)),
    };
}

export function PodcastToJSON(value?: Podcast | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'cover': value.cover,
        'id': value.id,
        'modified_at': value.modifiedAt === undefined ? undefined : (value.modifiedAt.toISOString()),
        'created_at': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'query': PodcastPQueryToJSON(value.query),
        'translations': value.translations === undefined ? undefined : (value.translations === null ? null : (value.translations as Array<any>).map(PodcastPodcastTranslationToJSON)),
    };
}

