/* tslint:disable */
/* eslint-disable */
/**
 * BMM Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ProjectRulesQueryRulesSection } from './ProjectRulesQueryRulesSection';
import {
    ProjectRulesQueryRulesSectionFromJSON,
    ProjectRulesQueryRulesSectionFromJSONTyped,
    ProjectRulesQueryRulesSectionToJSON,
} from './ProjectRulesQueryRulesSection';

/**
 * 
 * @export
 * @interface ProjectRulesQueryRules
 */
export interface ProjectRulesQueryRules {
    /**
     * 
     * @type {string}
     * @memberof ProjectRulesQueryRules
     */
    pageTitle?: string | null;
    /**
     * 
     * @type {Array<ProjectRulesQueryRulesSection>}
     * @memberof ProjectRulesQueryRules
     */
    sections?: Array<ProjectRulesQueryRulesSection> | null;
}

/**
 * Check if a given object implements the ProjectRulesQueryRules interface.
 */
export function instanceOfProjectRulesQueryRules(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ProjectRulesQueryRulesFromJSON(json: any): ProjectRulesQueryRules {
    return ProjectRulesQueryRulesFromJSONTyped(json, false);
}

export function ProjectRulesQueryRulesFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectRulesQueryRules {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'pageTitle': !exists(json, 'page_title') ? undefined : json['page_title'],
        'sections': !exists(json, 'sections') ? undefined : (json['sections'] === null ? null : (json['sections'] as Array<any>).map(ProjectRulesQueryRulesSectionFromJSON)),
    };
}

export function ProjectRulesQueryRulesToJSON(value?: ProjectRulesQueryRules | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'page_title': value.pageTitle,
        'sections': value.sections === undefined ? undefined : (value.sections === null ? null : (value.sections as Array<any>).map(ProjectRulesQueryRulesSectionToJSON)),
    };
}

