/* tslint:disable */
/* eslint-disable */
/**
 * BMM Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ProjectChurchStatisticsQueryChurchStatisticsChurch } from './ProjectChurchStatisticsQueryChurchStatisticsChurch';
import {
    ProjectChurchStatisticsQueryChurchStatisticsChurchFromJSON,
    ProjectChurchStatisticsQueryChurchStatisticsChurchFromJSONTyped,
    ProjectChurchStatisticsQueryChurchStatisticsChurchToJSON,
} from './ProjectChurchStatisticsQueryChurchStatisticsChurch';

/**
 * 
 * @export
 * @interface ProjectChurchStatisticsQueryChurchStatistics
 */
export interface ProjectChurchStatisticsQueryChurchStatistics {
    /**
     * 
     * @type {string}
     * @memberof ProjectChurchStatisticsQueryChurchStatistics
     */
    churchName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProjectChurchStatisticsQueryChurchStatistics
     */
    churchId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ProjectChurchStatisticsQueryChurchStatistics
     */
    limitToYouth?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ProjectChurchStatisticsQueryChurchStatistics
     */
    hasBmmAccountPercent13to17?: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectChurchStatisticsQueryChurchStatistics
     */
    hasBmmAccountPercent18to25?: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectChurchStatisticsQueryChurchStatistics
     */
    hasBmmAccountPercent26to35?: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectChurchStatisticsQueryChurchStatistics
     */
    hasBmmAccountPercentYouth?: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectChurchStatisticsQueryChurchStatistics
     */
    percent13to17?: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectChurchStatisticsQueryChurchStatistics
     */
    percent18to25?: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectChurchStatisticsQueryChurchStatistics
     */
    percent26to35?: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectChurchStatisticsQueryChurchStatistics
     */
    percentYouth?: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectChurchStatisticsQueryChurchStatistics
     */
    onTrackPercent13to17?: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectChurchStatisticsQueryChurchStatistics
     */
    onTrackPercent18to25?: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectChurchStatisticsQueryChurchStatistics
     */
    onTrackPercent26to35?: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectChurchStatisticsQueryChurchStatistics
     */
    onTrackPercentYouth?: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectChurchStatisticsQueryChurchStatistics
     */
    lastWeekPercent13to17?: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectChurchStatisticsQueryChurchStatistics
     */
    lastWeekPercent18to25?: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectChurchStatisticsQueryChurchStatistics
     */
    lastWeekPercent26to35?: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectChurchStatisticsQueryChurchStatistics
     */
    lastWeekPercentYouth?: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectChurchStatisticsQueryChurchStatistics
     */
    sinceFebruary12Percent13to17?: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectChurchStatisticsQueryChurchStatistics
     */
    sinceFebruary12Percent18to25?: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectChurchStatisticsQueryChurchStatistics
     */
    sinceFebruary12Percent26to35?: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectChurchStatisticsQueryChurchStatistics
     */
    sinceFebruary12PercentYouth?: number;
    /**
     * 
     * @type {Array<ProjectChurchStatisticsQueryChurchStatisticsChurch>}
     * @memberof ProjectChurchStatisticsQueryChurchStatistics
     */
    availableChurches?: Array<ProjectChurchStatisticsQueryChurchStatisticsChurch> | null;
}

/**
 * Check if a given object implements the ProjectChurchStatisticsQueryChurchStatistics interface.
 */
export function instanceOfProjectChurchStatisticsQueryChurchStatistics(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ProjectChurchStatisticsQueryChurchStatisticsFromJSON(json: any): ProjectChurchStatisticsQueryChurchStatistics {
    return ProjectChurchStatisticsQueryChurchStatisticsFromJSONTyped(json, false);
}

export function ProjectChurchStatisticsQueryChurchStatisticsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectChurchStatisticsQueryChurchStatistics {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'churchName': !exists(json, 'church_name') ? undefined : json['church_name'],
        'churchId': !exists(json, 'church_id') ? undefined : json['church_id'],
        'limitToYouth': !exists(json, 'limit_to_youth') ? undefined : json['limit_to_youth'],
        'hasBmmAccountPercent13to17': !exists(json, 'has_bmm_account_percent13to17') ? undefined : json['has_bmm_account_percent13to17'],
        'hasBmmAccountPercent18to25': !exists(json, 'has_bmm_account_percent18to25') ? undefined : json['has_bmm_account_percent18to25'],
        'hasBmmAccountPercent26to35': !exists(json, 'has_bmm_account_percent26to35') ? undefined : json['has_bmm_account_percent26to35'],
        'hasBmmAccountPercentYouth': !exists(json, 'has_bmm_account_percent_youth') ? undefined : json['has_bmm_account_percent_youth'],
        'percent13to17': !exists(json, 'percent13to17') ? undefined : json['percent13to17'],
        'percent18to25': !exists(json, 'percent18to25') ? undefined : json['percent18to25'],
        'percent26to35': !exists(json, 'percent26to35') ? undefined : json['percent26to35'],
        'percentYouth': !exists(json, 'percent_youth') ? undefined : json['percent_youth'],
        'onTrackPercent13to17': !exists(json, 'on_track_percent13to17') ? undefined : json['on_track_percent13to17'],
        'onTrackPercent18to25': !exists(json, 'on_track_percent18to25') ? undefined : json['on_track_percent18to25'],
        'onTrackPercent26to35': !exists(json, 'on_track_percent26to35') ? undefined : json['on_track_percent26to35'],
        'onTrackPercentYouth': !exists(json, 'on_track_percent_youth') ? undefined : json['on_track_percent_youth'],
        'lastWeekPercent13to17': !exists(json, 'last_week_percent13to17') ? undefined : json['last_week_percent13to17'],
        'lastWeekPercent18to25': !exists(json, 'last_week_percent18to25') ? undefined : json['last_week_percent18to25'],
        'lastWeekPercent26to35': !exists(json, 'last_week_percent26to35') ? undefined : json['last_week_percent26to35'],
        'lastWeekPercentYouth': !exists(json, 'last_week_percent_youth') ? undefined : json['last_week_percent_youth'],
        'sinceFebruary12Percent13to17': !exists(json, 'since_february12_percent13to17') ? undefined : json['since_february12_percent13to17'],
        'sinceFebruary12Percent18to25': !exists(json, 'since_february12_percent18to25') ? undefined : json['since_february12_percent18to25'],
        'sinceFebruary12Percent26to35': !exists(json, 'since_february12_percent26to35') ? undefined : json['since_february12_percent26to35'],
        'sinceFebruary12PercentYouth': !exists(json, 'since_february12_percent_youth') ? undefined : json['since_february12_percent_youth'],
        'availableChurches': !exists(json, 'available_churches') ? undefined : (json['available_churches'] === null ? null : (json['available_churches'] as Array<any>).map(ProjectChurchStatisticsQueryChurchStatisticsChurchFromJSON)),
    };
}

export function ProjectChurchStatisticsQueryChurchStatisticsToJSON(value?: ProjectChurchStatisticsQueryChurchStatistics | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'church_name': value.churchName,
        'church_id': value.churchId,
        'limit_to_youth': value.limitToYouth,
        'has_bmm_account_percent13to17': value.hasBmmAccountPercent13to17,
        'has_bmm_account_percent18to25': value.hasBmmAccountPercent18to25,
        'has_bmm_account_percent26to35': value.hasBmmAccountPercent26to35,
        'has_bmm_account_percent_youth': value.hasBmmAccountPercentYouth,
        'percent13to17': value.percent13to17,
        'percent18to25': value.percent18to25,
        'percent26to35': value.percent26to35,
        'percent_youth': value.percentYouth,
        'on_track_percent13to17': value.onTrackPercent13to17,
        'on_track_percent18to25': value.onTrackPercent18to25,
        'on_track_percent26to35': value.onTrackPercent26to35,
        'on_track_percent_youth': value.onTrackPercentYouth,
        'last_week_percent13to17': value.lastWeekPercent13to17,
        'last_week_percent18to25': value.lastWeekPercent18to25,
        'last_week_percent26to35': value.lastWeekPercent26to35,
        'last_week_percent_youth': value.lastWeekPercentYouth,
        'since_february12_percent13to17': value.sinceFebruary12Percent13to17,
        'since_february12_percent18to25': value.sinceFebruary12Percent18to25,
        'since_february12_percent26to35': value.sinceFebruary12Percent26to35,
        'since_february12_percent_youth': value.sinceFebruary12PercentYouth,
        'available_churches': value.availableChurches === undefined ? undefined : (value.availableChurches === null ? null : (value.availableChurches as Array<any>).map(ProjectChurchStatisticsQueryChurchStatisticsChurchToJSON)),
    };
}

