/* tslint:disable */
/* eslint-disable */
/**
 * BMM Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AchievementModel } from './AchievementModel';
import {
    AchievementModelFromJSON,
    AchievementModelFromJSONTyped,
    AchievementModelToJSON,
} from './AchievementModel';

/**
 * 
 * @export
 * @interface ProjectBoxV2
 */
export interface ProjectBoxV2 {
    /**
     * 
     * @type {number}
     * @memberof ProjectBoxV2
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof ProjectBoxV2
     */
    readonly type: ProjectBoxV2TypeEnum;
    /**
     * 
     * @type {string}
     * @memberof ProjectBoxV2
     */
    title?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ProjectBoxV2
     */
    points?: number;
    /**
     * 
     * @type {string}
     * @memberof ProjectBoxV2
     */
    pointsDescription?: string | null;
    /**
     * 
     * @type {Array<AchievementModel>}
     * @memberof ProjectBoxV2
     */
    achievements?: Array<AchievementModel> | null;
    /**
     * 
     * @type {string}
     * @memberof ProjectBoxV2
     */
    rulesLinkTitle?: string | null;
}


/**
 * @export
 */
export const ProjectBoxV2TypeEnum = {
    ProjectBoxV2: 'project_box_v2'
} as const;
export type ProjectBoxV2TypeEnum = typeof ProjectBoxV2TypeEnum[keyof typeof ProjectBoxV2TypeEnum];


/**
 * Check if a given object implements the ProjectBoxV2 interface.
 */
export function instanceOfProjectBoxV2(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "type" in value;

    return isInstance;
}

export function ProjectBoxV2FromJSON(json: any): ProjectBoxV2 {
    return ProjectBoxV2FromJSONTyped(json, false);
}

export function ProjectBoxV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectBoxV2 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'type': json['type'],
        'title': !exists(json, 'title') ? undefined : json['title'],
        'points': !exists(json, 'points') ? undefined : json['points'],
        'pointsDescription': !exists(json, 'points_description') ? undefined : json['points_description'],
        'achievements': !exists(json, 'achievements') ? undefined : (json['achievements'] === null ? null : (json['achievements'] as Array<any>).map(AchievementModelFromJSON)),
        'rulesLinkTitle': !exists(json, 'rules_link_title') ? undefined : json['rules_link_title'],
    };
}

export function ProjectBoxV2ToJSON(value?: ProjectBoxV2 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'title': value.title,
        'points': value.points,
        'points_description': value.pointsDescription,
        'achievements': value.achievements === undefined ? undefined : (value.achievements === null ? null : (value.achievements as Array<any>).map(AchievementModelToJSON)),
        'rules_link_title': value.rulesLinkTitle,
    };
}

