/* tslint:disable */
/* eslint-disable */
/**
 * BMM Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BibleBookEnum } from './BibleBookEnum';
import {
    BibleBookEnumFromJSON,
    BibleBookEnumFromJSONTyped,
    BibleBookEnumToJSON,
} from './BibleBookEnum';

/**
 * 
 * @export
 * @interface TrackModelRelation
 */
export interface TrackModelRelation {
    /**
     * 
     * @type {string}
     * @memberof TrackModelRelation
     */
    type?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TrackModelRelation
     */
    comment?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TrackModelRelation
     */
    name?: string | null;
    /**
     * 
     * @type {number}
     * @memberof TrackModelRelation
     */
    timestamp?: number | null;
    /**
     * 
     * @type {number}
     * @memberof TrackModelRelation
     */
    id?: number | null;
    /**
     * 
     * @type {string}
     * @memberof TrackModelRelation
     */
    url?: string | null;
    /**
     * 
     * @type {BibleBookEnum}
     * @memberof TrackModelRelation
     */
    book?: BibleBookEnum;
    /**
     * 
     * @type {number}
     * @memberof TrackModelRelation
     */
    chapter?: number | null;
    /**
     * 
     * @type {number}
     * @memberof TrackModelRelation
     */
    verse?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof TrackModelRelation
     */
    hasListened?: boolean;
}

/**
 * Check if a given object implements the TrackModelRelation interface.
 */
export function instanceOfTrackModelRelation(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TrackModelRelationFromJSON(json: any): TrackModelRelation {
    return TrackModelRelationFromJSONTyped(json, false);
}

export function TrackModelRelationFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrackModelRelation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': !exists(json, 'type') ? undefined : json['type'],
        'comment': !exists(json, 'comment') ? undefined : json['comment'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'timestamp': !exists(json, 'timestamp') ? undefined : json['timestamp'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'url': !exists(json, 'url') ? undefined : json['url'],
        'book': !exists(json, 'book') ? undefined : BibleBookEnumFromJSON(json['book']),
        'chapter': !exists(json, 'chapter') ? undefined : json['chapter'],
        'verse': !exists(json, 'verse') ? undefined : json['verse'],
        'hasListened': !exists(json, 'has_listened') ? undefined : json['has_listened'],
    };
}

export function TrackModelRelationToJSON(value?: TrackModelRelation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'comment': value.comment,
        'name': value.name,
        'timestamp': value.timestamp,
        'id': value.id,
        'url': value.url,
        'book': BibleBookEnumToJSON(value.book),
        'chapter': value.chapter,
        'verse': value.verse,
        'has_listened': value.hasListened,
    };
}

