/* tslint:disable */
/* eslint-disable */
/**
 * BMM Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { LanguageEnum } from './LanguageEnum';
import {
    LanguageEnumFromJSON,
    LanguageEnumFromJSONTyped,
    LanguageEnumToJSON,
} from './LanguageEnum';
import type { TrackModelBibleRelation } from './TrackModelBibleRelation';
import {
    TrackModelBibleRelationFromJSON,
    TrackModelBibleRelationFromJSONTyped,
    TrackModelBibleRelationToJSON,
} from './TrackModelBibleRelation';
import type { TrackModelContributorRelation } from './TrackModelContributorRelation';
import {
    TrackModelContributorRelationFromJSON,
    TrackModelContributorRelationFromJSONTyped,
    TrackModelContributorRelationToJSON,
} from './TrackModelContributorRelation';
import type { TrackModelExternalRelation } from './TrackModelExternalRelation';
import {
    TrackModelExternalRelationFromJSON,
    TrackModelExternalRelationFromJSONTyped,
    TrackModelExternalRelationToJSON,
} from './TrackModelExternalRelation';
import type { TrackModelMedium } from './TrackModelMedium';
import {
    TrackModelMediumFromJSON,
    TrackModelMediumFromJSONTyped,
    TrackModelMediumToJSON,
} from './TrackModelMedium';
import type { TrackModelRelation } from './TrackModelRelation';
import {
    TrackModelRelationFromJSON,
    TrackModelRelationFromJSONTyped,
    TrackModelRelationToJSON,
} from './TrackModelRelation';
import type { TrackModelSongbookRelation } from './TrackModelSongbookRelation';
import {
    TrackModelSongbookRelationFromJSON,
    TrackModelSongbookRelationFromJSONTyped,
    TrackModelSongbookRelationToJSON,
} from './TrackModelSongbookRelation';
import type { TrackModelTrackMeta } from './TrackModelTrackMeta';
import {
    TrackModelTrackMetaFromJSON,
    TrackModelTrackMetaFromJSONTyped,
    TrackModelTrackMetaToJSON,
} from './TrackModelTrackMeta';
import type { TrackSubtype } from './TrackSubtype';
import {
    TrackSubtypeFromJSON,
    TrackSubtypeFromJSONTyped,
    TrackSubtypeToJSON,
} from './TrackSubtype';

/**
 * 
 * @export
 * @interface TrackModel
 */
export interface TrackModel {
    /**
     * 
     * @type {string}
     * @memberof TrackModel
     */
    comment?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TrackModel
     */
    cover?: string | null;
    /**
     * 
     * @type {number}
     * @memberof TrackModel
     */
    id: number;
    /**
     * 
     * @type {boolean}
     * @memberof TrackModel
     */
    isVisible?: boolean;
    /**
     * 
     * @type {number}
     * @memberof TrackModel
     */
    order?: number;
    /**
     * 
     * @type {number}
     * @memberof TrackModel
     */
    parentId: number;
    /**
     * 
     * @type {Date}
     * @memberof TrackModel
     */
    publishedAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof TrackModel
     */
    recordedAt: Date;
    /**
     * 
     * @type {Array<TrackModelRelation>}
     * @memberof TrackModel
     */
    rel?: Array<TrackModelRelation> | null;
    /**
     * 
     * @type {Array<TrackModelBibleRelation>}
     * @memberof TrackModel
     */
    readonly bibleRelations?: Array<TrackModelBibleRelation> | null;
    /**
     * 
     * @type {Array<TrackModelExternalRelation>}
     * @memberof TrackModel
     */
    readonly externalRelations?: Array<TrackModelExternalRelation> | null;
    /**
     * 
     * @type {Array<TrackModelContributorRelation>}
     * @memberof TrackModel
     */
    readonly contributors?: Array<TrackModelContributorRelation> | null;
    /**
     * 
     * @type {Array<TrackModelSongbookRelation>}
     * @memberof TrackModel
     */
    readonly songbookRelations?: Array<TrackModelSongbookRelation> | null;
    /**
     * 
     * @type {TrackSubtype}
     * @memberof TrackModel
     */
    subtype: TrackSubtype;
    /**
     * 
     * @type {Array<string>}
     * @memberof TrackModel
     */
    tags: Array<string>;
    /**
     * 
     * @type {TrackModelTrackMeta}
     * @memberof TrackModel
     */
    meta: TrackModelTrackMeta;
    /**
     * 
     * @type {string}
     * @memberof TrackModel
     */
    readonly type: TrackModelTypeEnum;
    /**
     * 
     * @type {Array<LanguageEnum>}
     * @memberof TrackModel
     */
    languages: Array<LanguageEnum>;
    /**
     * 
     * @type {LanguageEnum}
     * @memberof TrackModel
     */
    language: LanguageEnum;
    /**
     * 
     * @type {Array<LanguageEnum>}
     * @memberof TrackModel
     */
    transcriptionLanguages: Array<LanguageEnum>;
    /**
     * 
     * @type {string}
     * @memberof TrackModel
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TrackModel
     */
    publisher?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TrackModel
     */
    copyright?: string | null;
    /**
     * 
     * @type {Array<TrackModelMedium>}
     * @memberof TrackModel
     */
    media?: Array<TrackModelMedium> | null;
    /**
     * 
     * @type {boolean}
     * @memberof TrackModel
     */
    hasListened?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof TrackModel
     */
    hasTranscription?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof TrackModel
     */
    isLiked?: boolean;
}


/**
 * @export
 */
export const TrackModelTypeEnum = {
    Track: 'track'
} as const;
export type TrackModelTypeEnum = typeof TrackModelTypeEnum[keyof typeof TrackModelTypeEnum];


/**
 * Check if a given object implements the TrackModel interface.
 */
export function instanceOfTrackModel(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "parentId" in value;
    isInstance = isInstance && "publishedAt" in value;
    isInstance = isInstance && "recordedAt" in value;
    isInstance = isInstance && "subtype" in value;
    isInstance = isInstance && "tags" in value;
    isInstance = isInstance && "meta" in value;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "languages" in value;
    isInstance = isInstance && "language" in value;
    isInstance = isInstance && "transcriptionLanguages" in value;

    return isInstance;
}

export function TrackModelFromJSON(json: any): TrackModel {
    return TrackModelFromJSONTyped(json, false);
}

export function TrackModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrackModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'comment': !exists(json, 'comment') ? undefined : json['comment'],
        'cover': !exists(json, 'cover') ? undefined : json['cover'],
        'id': json['id'],
        'isVisible': !exists(json, 'is_visible') ? undefined : json['is_visible'],
        'order': !exists(json, 'order') ? undefined : json['order'],
        'parentId': json['parent_id'],
        'publishedAt': (new Date(json['published_at'])),
        'recordedAt': (new Date(json['recorded_at'])),
        'rel': !exists(json, 'rel') ? undefined : (json['rel'] === null ? null : (json['rel'] as Array<any>).map(TrackModelRelationFromJSON)),
        'bibleRelations': !exists(json, 'bible_relations') ? undefined : (json['bible_relations'] === null ? null : (json['bible_relations'] as Array<any>).map(TrackModelBibleRelationFromJSON)),
        'externalRelations': !exists(json, 'external_relations') ? undefined : (json['external_relations'] === null ? null : (json['external_relations'] as Array<any>).map(TrackModelExternalRelationFromJSON)),
        'contributors': !exists(json, 'contributors') ? undefined : (json['contributors'] === null ? null : (json['contributors'] as Array<any>).map(TrackModelContributorRelationFromJSON)),
        'songbookRelations': !exists(json, 'songbook_relations') ? undefined : (json['songbook_relations'] === null ? null : (json['songbook_relations'] as Array<any>).map(TrackModelSongbookRelationFromJSON)),
        'subtype': TrackSubtypeFromJSON(json['subtype']),
        'tags': json['tags'],
        'meta': TrackModelTrackMetaFromJSON(json['_meta']),
        'type': json['type'],
        'languages': ((json['languages'] as Array<any>).map(LanguageEnumFromJSON)),
        'language': LanguageEnumFromJSON(json['language']),
        'transcriptionLanguages': ((json['transcription_languages'] as Array<any>).map(LanguageEnumFromJSON)),
        'title': !exists(json, 'title') ? undefined : json['title'],
        'publisher': !exists(json, 'publisher') ? undefined : json['publisher'],
        'copyright': !exists(json, 'copyright') ? undefined : json['copyright'],
        'media': !exists(json, 'media') ? undefined : (json['media'] === null ? null : (json['media'] as Array<any>).map(TrackModelMediumFromJSON)),
        'hasListened': !exists(json, 'has_listened') ? undefined : json['has_listened'],
        'hasTranscription': !exists(json, 'has_transcription') ? undefined : json['has_transcription'],
        'isLiked': !exists(json, 'is_liked') ? undefined : json['is_liked'],
    };
}

export function TrackModelToJSON(value?: TrackModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'comment': value.comment,
        'cover': value.cover,
        'id': value.id,
        'is_visible': value.isVisible,
        'order': value.order,
        'parent_id': value.parentId,
        'published_at': (value.publishedAt.toISOString()),
        'recorded_at': (value.recordedAt.toISOString()),
        'rel': value.rel === undefined ? undefined : (value.rel === null ? null : (value.rel as Array<any>).map(TrackModelRelationToJSON)),
        'subtype': TrackSubtypeToJSON(value.subtype),
        'tags': value.tags,
        '_meta': TrackModelTrackMetaToJSON(value.meta),
        'languages': ((value.languages as Array<any>).map(LanguageEnumToJSON)),
        'language': LanguageEnumToJSON(value.language),
        'transcription_languages': ((value.transcriptionLanguages as Array<any>).map(LanguageEnumToJSON)),
        'title': value.title,
        'publisher': value.publisher,
        'copyright': value.copyright,
        'media': value.media === undefined ? undefined : (value.media === null ? null : (value.media as Array<any>).map(TrackModelMediumToJSON)),
        'has_listened': value.hasListened,
        'has_transcription': value.hasTranscription,
        'is_liked': value.isLiked,
    };
}

