/* tslint:disable */
/* eslint-disable */
/**
 * BMM Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TrackListReference
 */
export interface TrackListReference {
    /**
     * 
     * @type {number}
     * @memberof TrackListReference
     */
    id?: number;
}

/**
 * Check if a given object implements the TrackListReference interface.
 */
export function instanceOfTrackListReference(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TrackListReferenceFromJSON(json: any): TrackListReference {
    return TrackListReferenceFromJSONTyped(json, false);
}

export function TrackListReferenceFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrackListReference {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function TrackListReferenceToJSON(value?: TrackListReference | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
    };
}

