/* tslint:disable */
/* eslint-disable */
/**
 * BMM Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TrackModelParent } from './TrackModelParent';
import {
    TrackModelParentFromJSON,
    TrackModelParentFromJSONTyped,
    TrackModelParentToJSON,
} from './TrackModelParent';

/**
 * 
 * @export
 * @interface TrackModelTrackMeta
 */
export interface TrackModelTrackMeta {
    /**
     * 
     * @type {TrackModelParent}
     * @memberof TrackModelTrackMeta
     */
    parent?: TrackModelParent;
    /**
     * 
     * @type {TrackModelParent}
     * @memberof TrackModelTrackMeta
     */
    rootParent?: TrackModelParent;
    /**
     * 
     * @type {number}
     * @memberof TrackModelTrackMeta
     */
    rootParentId?: number;
    /**
     * 
     * @type {Date}
     * @memberof TrackModelTrackMeta
     */
    modifiedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof TrackModelTrackMeta
     */
    modifiedBy?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof TrackModelTrackMeta
     */
    isVisible?: boolean;
    /**
     * 
     * @type {string}
     * @memberof TrackModelTrackMeta
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TrackModelTrackMeta
     */
    language?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TrackModelTrackMeta
     */
    album?: string | null;
    /**
     * 
     * @type {number}
     * @memberof TrackModelTrackMeta
     */
    tracknumber?: number;
    /**
     * 
     * @type {string}
     * @memberof TrackModelTrackMeta
     */
    artist?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TrackModelTrackMeta
     */
    lyricist?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TrackModelTrackMeta
     */
    composer?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TrackModelTrackMeta
     */
    publisher?: string | null;
    /**
     * 
     * @type {number}
     * @memberof TrackModelTrackMeta
     */
    itunescompilation?: number;
    /**
     * 
     * @type {string}
     * @memberof TrackModelTrackMeta
     */
    attachedPicture?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TrackModelTrackMeta
     */
    time?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TrackModelTrackMeta
     */
    date?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TrackModelTrackMeta
     */
    year?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TrackModelTrackMeta
     */
    copyright?: string | null;
}

/**
 * Check if a given object implements the TrackModelTrackMeta interface.
 */
export function instanceOfTrackModelTrackMeta(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TrackModelTrackMetaFromJSON(json: any): TrackModelTrackMeta {
    return TrackModelTrackMetaFromJSONTyped(json, false);
}

export function TrackModelTrackMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrackModelTrackMeta {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'parent': !exists(json, 'parent') ? undefined : TrackModelParentFromJSON(json['parent']),
        'rootParent': !exists(json, 'rootParent') ? undefined : TrackModelParentFromJSON(json['rootParent']),
        'rootParentId': !exists(json, 'rootParentId') ? undefined : json['rootParentId'],
        'modifiedAt': !exists(json, 'modifiedAt') ? undefined : (new Date(json['modifiedAt'])),
        'modifiedBy': !exists(json, 'modifiedBy') ? undefined : json['modifiedBy'],
        'isVisible': !exists(json, 'isVisible') ? undefined : json['isVisible'],
        'title': !exists(json, 'title') ? undefined : json['title'],
        'language': !exists(json, 'language') ? undefined : json['language'],
        'album': !exists(json, 'album') ? undefined : json['album'],
        'tracknumber': !exists(json, 'tracknumber') ? undefined : json['tracknumber'],
        'artist': !exists(json, 'artist') ? undefined : json['artist'],
        'lyricist': !exists(json, 'lyricist') ? undefined : json['lyricist'],
        'composer': !exists(json, 'composer') ? undefined : json['composer'],
        'publisher': !exists(json, 'publisher') ? undefined : json['publisher'],
        'itunescompilation': !exists(json, 'itunescompilation') ? undefined : json['itunescompilation'],
        'attachedPicture': !exists(json, 'attachedPicture') ? undefined : json['attachedPicture'],
        'time': !exists(json, 'time') ? undefined : json['time'],
        'date': !exists(json, 'date') ? undefined : json['date'],
        'year': !exists(json, 'year') ? undefined : json['year'],
        'copyright': !exists(json, 'copyright') ? undefined : json['copyright'],
    };
}

export function TrackModelTrackMetaToJSON(value?: TrackModelTrackMeta | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'parent': TrackModelParentToJSON(value.parent),
        'rootParent': TrackModelParentToJSON(value.rootParent),
        'rootParentId': value.rootParentId,
        'modifiedAt': value.modifiedAt === undefined ? undefined : (value.modifiedAt.toISOString()),
        'modifiedBy': value.modifiedBy,
        'isVisible': value.isVisible,
        'title': value.title,
        'language': value.language,
        'album': value.album,
        'tracknumber': value.tracknumber,
        'artist': value.artist,
        'lyricist': value.lyricist,
        'composer': value.composer,
        'publisher': value.publisher,
        'itunescompilation': value.itunescompilation,
        'attachedPicture': value.attachedPicture,
        'time': value.time,
        'date': value.date,
        'year': value.year,
        'copyright': value.copyright,
    };
}

