/* tslint:disable */
/* eslint-disable */
/**
 * BMM Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const TrackSubtype = {
    Song: 'song',
    Speech: 'speech',
    Audiobook: 'audiobook',
    Singsong: 'singsong',
    Exegesis: 'exegesis',
    Video: 'video',
    Live: 'live'
} as const;
export type TrackSubtype = typeof TrackSubtype[keyof typeof TrackSubtype];


export function TrackSubtypeFromJSON(json: any): TrackSubtype {
    return TrackSubtypeFromJSONTyped(json, false);
}

export function TrackSubtypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrackSubtype {
    return json as TrackSubtype;
}

export function TrackSubtypeToJSON(value?: TrackSubtype | null): any {
    return value as any;
}

