/* tslint:disable */
/* eslint-disable */
/**
 * BMM Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    HttpValidationProblemDetails,
    instanceOfHttpValidationProblemDetails,
    HttpValidationProblemDetailsFromJSON,
    HttpValidationProblemDetailsFromJSONTyped,
    HttpValidationProblemDetailsToJSON,
} from './HttpValidationProblemDetails';
import {
    ProblemDetails,
    instanceOfProblemDetails,
    ProblemDetailsFromJSON,
    ProblemDetailsFromJSONTyped,
    ProblemDetailsToJSON,
} from './ProblemDetails';

/**
 * @type TrackCollectionIdUnfollowPost404Response
 * 
 * @export
 */
export type TrackCollectionIdUnfollowPost404Response = HttpValidationProblemDetails | ProblemDetails;

export function TrackCollectionIdUnfollowPost404ResponseFromJSON(json: any): TrackCollectionIdUnfollowPost404Response {
    return TrackCollectionIdUnfollowPost404ResponseFromJSONTyped(json, false);
}

export function TrackCollectionIdUnfollowPost404ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrackCollectionIdUnfollowPost404Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...HttpValidationProblemDetailsFromJSONTyped(json, true), ...ProblemDetailsFromJSONTyped(json, true) };
}

export function TrackCollectionIdUnfollowPost404ResponseToJSON(value?: TrackCollectionIdUnfollowPost404Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    if (instanceOfHttpValidationProblemDetails(value)) {
        return HttpValidationProblemDetailsToJSON(value as HttpValidationProblemDetails);
    }
    if (instanceOfProblemDetails(value)) {
        return ProblemDetailsToJSON(value as ProblemDetails);
    }

    return {};
}

