/* tslint:disable */
/* eslint-disable */
/**
 * BMM Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { LanguageEnum } from './LanguageEnum';
import {
    LanguageEnumFromJSON,
    LanguageEnumFromJSONTyped,
    LanguageEnumToJSON,
} from './LanguageEnum';

/**
 * 
 * @export
 * @interface TrackReference
 */
export interface TrackReference {
    /**
     * 
     * @type {number}
     * @memberof TrackReference
     */
    id?: number;
    /**
     * 
     * @type {LanguageEnum}
     * @memberof TrackReference
     */
    language?: LanguageEnum;
}

/**
 * Check if a given object implements the TrackReference interface.
 */
export function instanceOfTrackReference(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TrackReferenceFromJSON(json: any): TrackReference {
    return TrackReferenceFromJSONTyped(json, false);
}

export function TrackReferenceFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrackReference {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'language': !exists(json, 'language') ? undefined : LanguageEnumFromJSON(json['language']),
    };
}

export function TrackReferenceToJSON(value?: TrackReference | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'language': LanguageEnumToJSON(value.language),
    };
}

