/* tslint:disable */
/* eslint-disable */
/**
 * BMM Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TrackModelTrackContributorType } from './TrackModelTrackContributorType';
import {
    TrackModelTrackContributorTypeFromJSON,
    TrackModelTrackContributorTypeFromJSONTyped,
    TrackModelTrackContributorTypeToJSON,
} from './TrackModelTrackContributorType';

/**
 * 
 * @export
 * @interface TrackModelContributorRelation
 */
export interface TrackModelContributorRelation {
    /**
     * 
     * @type {TrackModelTrackContributorType}
     * @memberof TrackModelContributorRelation
     */
    type?: TrackModelTrackContributorType;
    /**
     * 
     * @type {number}
     * @memberof TrackModelContributorRelation
     */
    id?: number | null;
    /**
     * 
     * @type {string}
     * @memberof TrackModelContributorRelation
     */
    name?: string | null;
}

/**
 * Check if a given object implements the TrackModelContributorRelation interface.
 */
export function instanceOfTrackModelContributorRelation(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TrackModelContributorRelationFromJSON(json: any): TrackModelContributorRelation {
    return TrackModelContributorRelationFromJSONTyped(json, false);
}

export function TrackModelContributorRelationFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrackModelContributorRelation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': !exists(json, 'type') ? undefined : TrackModelTrackContributorTypeFromJSON(json['type']),
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function TrackModelContributorRelationToJSON(value?: TrackModelContributorRelation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': TrackModelTrackContributorTypeToJSON(value.type),
        'id': value.id,
        'name': value.name,
    };
}

