/* tslint:disable */
/* eslint-disable */
/**
 * BMM Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TrackModelMediumFile
 */
export interface TrackModelMediumFile {
    /**
     * 
     * @type {string}
     * @memberof TrackModelMediumFile
     */
    mimeType?: string | null;
    /**
     * 
     * @type {number}
     * @memberof TrackModelMediumFile
     */
    size?: number;
    /**
     * 
     * @type {number}
     * @memberof TrackModelMediumFile
     */
    duration?: number;
    /**
     * 
     * @type {string}
     * @memberof TrackModelMediumFile
     */
    url?: string | null;
}

/**
 * Check if a given object implements the TrackModelMediumFile interface.
 */
export function instanceOfTrackModelMediumFile(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TrackModelMediumFileFromJSON(json: any): TrackModelMediumFile {
    return TrackModelMediumFileFromJSONTyped(json, false);
}

export function TrackModelMediumFileFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrackModelMediumFile {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'mimeType': !exists(json, 'mime_type') ? undefined : json['mime_type'],
        'size': !exists(json, 'size') ? undefined : json['size'],
        'duration': !exists(json, 'duration') ? undefined : json['duration'],
        'url': !exists(json, 'url') ? undefined : json['url'],
    };
}

export function TrackModelMediumFileToJSON(value?: TrackModelMediumFile | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'mime_type': value.mimeType,
        'size': value.size,
        'duration': value.duration,
        'url': value.url,
    };
}

