/* tslint:disable */
/* eslint-disable */
/**
 * BMM Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TrackCollectionDetails
 */
export interface TrackCollectionDetails {
    /**
     * 
     * @type {number}
     * @memberof TrackCollectionDetails
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof TrackCollectionDetails
     */
    name?: string | null;
    /**
     * 
     * @type {number}
     * @memberof TrackCollectionDetails
     */
    trackCount?: number;
    /**
     * 
     * @type {number}
     * @memberof TrackCollectionDetails
     */
    followerCount?: number;
    /**
     * 
     * @type {string}
     * @memberof TrackCollectionDetails
     */
    authorName?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof TrackCollectionDetails
     */
    canEdit?: boolean;
}

/**
 * Check if a given object implements the TrackCollectionDetails interface.
 */
export function instanceOfTrackCollectionDetails(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TrackCollectionDetailsFromJSON(json: any): TrackCollectionDetails {
    return TrackCollectionDetailsFromJSONTyped(json, false);
}

export function TrackCollectionDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrackCollectionDetails {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'trackCount': !exists(json, 'trackCount') ? undefined : json['trackCount'],
        'followerCount': !exists(json, 'followerCount') ? undefined : json['followerCount'],
        'authorName': !exists(json, 'authorName') ? undefined : json['authorName'],
        'canEdit': !exists(json, 'canEdit') ? undefined : json['canEdit'],
    };
}

export function TrackCollectionDetailsToJSON(value?: TrackCollectionDetails | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'trackCount': value.trackCount,
        'followerCount': value.followerCount,
        'authorName': value.authorName,
        'canEdit': value.canEdit,
    };
}

