/* tslint:disable */
/* eslint-disable */
/**
 * BMM Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TrackCollectionShell
 */
export interface TrackCollectionShell {
    /**
     * 
     * @type {number}
     * @memberof TrackCollectionShell
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof TrackCollectionShell
     */
    name?: string | null;
    /**
     * 
     * @type {number}
     * @memberof TrackCollectionShell
     */
    trackCount?: number;
    /**
     * 
     * @type {number}
     * @memberof TrackCollectionShell
     */
    followerCount: number;
    /**
     * 
     * @type {string}
     * @memberof TrackCollectionShell
     */
    authorName?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof TrackCollectionShell
     */
    canEdit: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof TrackCollectionShell
     */
    useLikeIcon?: boolean;
}

/**
 * Check if a given object implements the TrackCollectionShell interface.
 */
export function instanceOfTrackCollectionShell(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "followerCount" in value;
    isInstance = isInstance && "canEdit" in value;

    return isInstance;
}

export function TrackCollectionShellFromJSON(json: any): TrackCollectionShell {
    return TrackCollectionShellFromJSONTyped(json, false);
}

export function TrackCollectionShellFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrackCollectionShell {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'trackCount': !exists(json, 'track_count') ? undefined : json['track_count'],
        'followerCount': json['follower_count'],
        'authorName': !exists(json, 'author_name') ? undefined : json['author_name'],
        'canEdit': json['can_edit'],
        'useLikeIcon': !exists(json, 'use_like_icon') ? undefined : json['use_like_icon'],
    };
}

export function TrackCollectionShellToJSON(value?: TrackCollectionShell | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'track_count': value.trackCount,
        'follower_count': value.followerCount,
        'author_name': value.authorName,
        'can_edit': value.canEdit,
        'use_like_icon': value.useLikeIcon,
    };
}

