/* tslint:disable */
/* eslint-disable */
/**
 * BMM Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const TranscriptionTranscriptionSource = {
    Mediabanken: 'Mediabanken',
    SongTreasures: 'SongTreasures',
    Manual: 'Manual',
    Telegraph: 'Telegraph'
} as const;
export type TranscriptionTranscriptionSource = typeof TranscriptionTranscriptionSource[keyof typeof TranscriptionTranscriptionSource];


export function TranscriptionTranscriptionSourceFromJSON(json: any): TranscriptionTranscriptionSource {
    return TranscriptionTranscriptionSourceFromJSONTyped(json, false);
}

export function TranscriptionTranscriptionSourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): TranscriptionTranscriptionSource {
    return json as TranscriptionTranscriptionSource;
}

export function TranscriptionTranscriptionSourceToJSON(value?: TranscriptionTranscriptionSource | null): any {
    return value as any;
}

