/* tslint:disable */
/* eslint-disable */
/**
 * BMM Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TrackReference } from './TrackReference';
import {
    TrackReferenceFromJSON,
    TrackReferenceFromJSONTyped,
    TrackReferenceToJSON,
} from './TrackReference';

/**
 * 
 * @export
 * @interface UpdateTrackCollectionCommand
 */
export interface UpdateTrackCollectionCommand {
    /**
     * 
     * @type {number}
     * @memberof UpdateTrackCollectionCommand
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof UpdateTrackCollectionCommand
     */
    name?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof UpdateTrackCollectionCommand
     * @deprecated
     */
    access?: Array<string> | null;
    /**
     * 
     * @type {Array<TrackReference>}
     * @memberof UpdateTrackCollectionCommand
     */
    trackReferences?: Array<TrackReference> | null;
}

/**
 * Check if a given object implements the UpdateTrackCollectionCommand interface.
 */
export function instanceOfUpdateTrackCollectionCommand(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UpdateTrackCollectionCommandFromJSON(json: any): UpdateTrackCollectionCommand {
    return UpdateTrackCollectionCommandFromJSONTyped(json, false);
}

export function UpdateTrackCollectionCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateTrackCollectionCommand {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'access': !exists(json, 'access') ? undefined : json['access'],
        'trackReferences': !exists(json, 'track_references') ? undefined : (json['track_references'] === null ? null : (json['track_references'] as Array<any>).map(TrackReferenceFromJSON)),
    };
}

export function UpdateTrackCollectionCommandToJSON(value?: UpdateTrackCollectionCommand | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'access': value.access,
        'track_references': value.trackReferences === undefined ? undefined : (value.trackReferences === null ? null : (value.trackReferences as Array<any>).map(TrackReferenceToJSON)),
    };
}

